### ISSUE TITLE
🌈 显示优化 | 多页面滚动条状态保持

### ISSUE THREAD

**Issue by 364244332** [d2-projects/d2-admin#104]
多页面情况下，切换tab，从A模块切到B模块，再从B切回A，A模块滚动条位置无法保持，是否可以增加滚动条状态保持的功能

**Comment by FairyEver** [comment]
正在准备开发下一个大版本，暂时不计划增加这个功能，你可以自己改造 `d2-container` 组件实现这个功能，也欢迎你的 pr
