### ISSUE TITLE
新增的同时，新增按钮

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#105]
大神好，我想请教一下，我在点击新增按钮的时候，在新增数据的同时，把编辑按钮和删除按钮一起新增到数据表格中，谢谢大神

**Comment by FairyEver** [comment]
请到 [https://github.com/d2-projects/d2-crud/issues](https://github.com/d2-projects/d2-crud/issues) 提问，不是此项目
