### ISSUE TITLE
验证码机制

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#108]
想请教一下下面的情况如何实现：
最开始没有验证码验证情况。当账户或密码错误五次后才显示验证码进行验证登录

**Comment by FairyEver** [comment]
首先，这不是关于 D2Admin 的问题。

一种方案：用户如果输入密码错误后后端记录该用户输入错误的信息（不建议在前端记录，可以通过手段清空数据），如果达到5次之后返回给前端验证码图片的地址，前端接收到这个标志之后显示验证码，下次发送请求的时候必须携带验证码给后端校验。

**Comment by leoyuuuuu** [comment]
还想问问就是当账户密码无错误时隐藏，当错误超过五次时显示的方法，谢谢
