### ISSUE TITLE
🤔 提问 | 怎么隐藏column

### ISSUE THREAD

**Issue by dannykhoo** [d2-projects/d2-admin#109]
不好意思新手的问题，试了好几个方法都不能，怎么才能隐藏 location 和 department的column

  tableQtyColumns: [{
                    key: "Location",
                    title: "Location",
                    sortable: true,
                    width: 100,
                    hidden: true
                },
                {
                    key: "Department",
                    title: "Department",
                    sortable: true,
                    width: 120,
                    hidden: true
                },
                {
                    key: "User",
                    title: "User",
                    sortable: true,
                    width: 130
                },
                {
                    key: "GRNo",
                    title: "GR No.",
                    sortable: true,
                },
                {
                    key: "Qty",
                    title: "Qty",
                    sortable: true,
                },

                {
                    key: "Cost",
                    title: "Cost",
                    sortable: true,
                },

            ],

**Comment by MarkChaLi** [comment]
同问如何解决
