### ISSUE TITLE
数据分页如何根据接口返回的总页数和总条数动态展示

### ISSUE THREAD

**Issue by kiner-tang** [d2-projects/d2-admin#110]
数据分页如何根据接口返回的总页数和总条数动态展示

目前使用分页是，都是根据data数组的长度来判断是否分页的，但实际开发中一般都是访问接口获取第一页数据的同时，接口会返回数据库中所有数据的条数和总页数，我们需要根据总条数和总页数动态的显示分页数量。在d2-admin中不知该如何设置，在文档中未找到介绍。

**Comment by FairyEver** [comment]
这不是 D2Admin 的范畴，这是你的业务代码，参考 [element 分页组件](http://element.eleme.io/#/zh-CN/component/pagination) 和 [element 表格组件](http://element.eleme.io/#/zh-CN/component/table)，这不是任何语言或者编程框架或者组件的问题，如果你有过开发经验，应该会知道怎样做。

> D2Admin 的示例业务页面表格数据 mock 中也有模拟返回分页信息。[https://github.com/d2-projects/d2-admin/blob/master/src/mock/api/demo/business/table/1/index.js](https://github.com/d2-projects/d2-admin/blob/master/src/mock/api/demo/business/table/1/index.js) 实际怎样设计还要看后端接口。
