### ISSUE TITLE
D2 CRUD 模糊查询功能

### ISSUE THREAD

**Issue by AnnQian** [d2-projects/d2-admin#111]
D2 CRUD 模糊查询功能

功能是对表格字段能进行模糊查询，但是增加自定义文本框后会在标题和新增按钮外，布局实在太过奇葩|||，希望能嵌入模糊差查询文本框的位置

**Comment by FairyEver** [comment]
crud 相关问题请转至 [https://github.com/d2-projects/d2-crud](https://github.com/d2-projects/d2-crud) 提 issue，此项目是 d2admin
