### ISSUE TITLE
🤔 提问 | 如何实现多国语言？

### ISSUE THREAD

**Issue by lichnow** [d2-projects/d2-admin#112]
请问这个后台怎么实现il8n国际化翻译呢？

**Comment by FairyEver** [comment]
默认建议将多国语设置放在 src/i18n 中。完整版示例里有相关示例 [https://github.com/d2-projects/d2-admin/blob/master/src/pages/demo/plugins/i18n/demo1.vue](https://github.com/d2-projects/d2-admin/blob/master/src/pages/demo/plugins/i18n/demo1.vue)。

默认已经帮你配置好相关 webpack 设置。具体的使用方式见 vue-i18n 文档。

**Comment by FairyEver** [comment]
通用组件请使用 element 自带的多国语功能，业务文字再使用上面的方案。
