### ISSUE TITLE
🔩 功能开发 | 能否支持移动响应式浏览

### ISSUE THREAD

**Issue by lichnow** [d2-projects/d2-admin#113]
请问这个框架能否支持移动浏览呢？

**Comment by FairyEver** [comment]
默认不支持，管理系统在移动端使用的情况较少，而且组件库 [element](http://element.eleme.io/#/zh-CN/component/installation) 的设计也不是为移动端准备的，所以暂不支持手机端。动手能力强的话可以自己修改，难度可能较大。
