### ISSUE TITLE
d2-crud弹窗下拉框取值问题

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#115]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 你的标题
```

如果需要，在这里描述具体内容
handleRowEdit ({ index, row }, done) {
      this.formOptions.saveLoading = true
      setTimeout(() => {
        console.log(this.formTemplate.role_name.component.props)
        //console.log(row)
		
		
		
		updateUser({
			user_id:row.user_id,
			username:row.username,
			password:row.password,
			name:row.name,
			role_id:row.role_id,
			dept_id:row.dept_id,
			phone:row.phone,
			remarks:row.remarks,
			status_str:row.status_str
		}).then(res => {
		  console.log(res);
		})
		.catch(err => {
		  // 异常情况
		})
		
        this.$message({
          message: '修改成功',
          type: 'success'
        })
        done()
        this.formOptions.saveLoading = false
      }, 300)
    },
大神，请教一下，怎么在这里内拿到弹窗内下拉框当前值的属性值啊

**Comment by FairyEver** [comment]
crud 的作者应该回答你了，此问题关闭，以后 crud 相关问题请到 [d2-crud](https://github.com/d2-projects/d2-crud) 项目提 issue，你发错了地方。
