### ISSUE TITLE
get不能向后端传递参数

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#118]
请教一下， 我用post可以向后端传递参数，但是用get不能向后端传递参数

**Comment by FairyEver** [comment]
你的代码呢？

**Comment by leoyuuuuu** [comment]
//  查询用户列表
	  resetUsers() {
		//console.log(this.filters.type);
		let roleId = "";
		for(let i = 0; i < this.roleOptions.length; i++) {
			if(this.filters.type == this.roleOptions[i].name) {
				roleId = this.roleOptions[i].role_id;
			}
		}
		//console.log(roleId);
		searchUser({
			role_id:roleId,
			keyword:this.filters.name
		}).then(res => {
		this.bookData = res.list;
		  //console.log(res.list);
		})
		.catch(err => {
		  // 异常情况
		})
	  },

接口代码按你的规则写在api内了

**Comment by FairyEver** [comment]
searchUser 部分的代码展示一下

**Comment by FairyEver** [comment]
控制台网络请求截图

**Comment by leoyuuuuu** [comment]
import request from '@/plugin/axios'

export function searchUser (data) {
  return request({
    url: 'http://192.168.0.118:8080/user/v1.0/user-list',
    method: 'get',
    data
  })
}

**Comment by FairyEver** [comment]
你的 axios 使用错了，按照官方示例对比 : [https://github.com/axios/axios#example](https://github.com/axios/axios#example)

另外请注意 issue 的 markdown 书写格式，你上面的回复应该这样写：

``` js
import request from '@/plugin/axios'

export function searchUser (data) {
  return request({
  	url: 'http://192.168.0.118:8080/user/v1.0/user-list',
  	method: 'get',
  	data
  })
}
```

**Comment by leoyuuuuu** [comment]
意思就是用下面这段代码
const axios = require('axios');

// Make a request for a user with a given ID
axios.get('/user?ID=12345')
  .then(function (response) {
    // handle success
    console.log(response);
  })
  .catch(function (error) {
    // handle error
    console.log(error);
  })
  .then(function () {
    // always executed
  });
向后端请求数据吗？

**Comment by FairyEver** [comment]
首先你上面的写法是可行的，但是不易扩展。

就在你摘抄的代码下面：

``` js
// Optionally the request above could also be done as
axios.get('/user', {
    params: {
      ID: 12345
    }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
    // always executed
  });
```

建议使用这种方式，和你上一段代码是等效的。你之前的错是 post 和 get 使用的同一种传参方式，实际上是不一样的，请仔细阅读文章。

**请注意 issue 的 markdown 书写格式**

**Comment by carolcoral** [comment]
我目前有两种方式可以通过get请求：
第一种：
```
import request from '@/plugin/axios'
export function get(params = {}) {
  return request({
    url: '/get',
    method: 'get',
    params
  })
}
```
第二种（因为这个项目是默认采用json方式发送数据，但是如果后端是通过字段接受需要使用qs来转换一下）：
```
import request from '@/plugin/axios'
import qs from 'qs'

export function get(data) {
  console.log(data)
  return request({
    url: '/get',
    method: 'get',
    transformRequest: [function (data) {
      return qs.stringify(data)
    }],
    data: data
  })
}
```
