### ISSUE TITLE
后端获取到的值不能循环给下拉框

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#119]
在page.vue中

<el-col class="toolbar" style="padding-bottom: 0; text-align: left">
		  <el-form :inline="true" :model="filters">
			<el-form-item label="所属角色" >
				<el-select placeholder="请选择" v-model="filters.type" prop="role_name" size="mini">
				  <el-option v-for="roleItem in roleOptions"
				   :key="roleItem.ZD_ID"
				   :value="roleItem.NAME">
				   </el-option>
				</el-select>
			</el-form-item>
			<el-form-item>
			  <el-button type="primary" size="mini">查询</el-button>
			</el-form-item>
		  </el-form>
		</el-col>

用

import { getUserDept } from '@/api/demo/user/getUserDept'

  getUserDept({
        
	}).then(res => {
		
		this.roleOptions = res.roleList;
		console.log(res.roleOptions);
	})
	.catch(err => {
	  // 异常情况
	})

不能把

[{ZD_ID: 3, REMARKS: "角色权限", NAME: "中心", PARENT_ID: 1}]

赋值给options

**Comment by FairyEver** [comment]
为什么不能赋值？请描述原因。

参考：

```
import { getUserDept } from '@/api/demo/user/getUserDept'

getUserDept({

}).then(res => {
	this.roleOptions = res.roleList.map(e => ({
		label: e.NAME,
		value: e.PARENT_ID
	}))
})
.catch(err => {
  // 异常情况
})
```
