### ISSUE TITLE
🖐 其它问题 | Vuex重度使用, 作为一个模板来使用, 确实比较重, 特别是作为一个非前端开发来说

### ISSUE THREAD

**Issue by koy-tome** [d2-projects/d2-admin#121]
看过很多的类似前端开发模板, vuex的使用希望还是可以简化使用. 一点建议, 请不要鄙视!!!

**Comment by FairyEver** [comment]
首先不会鄙视你 👍 

每个 issue 都是反馈大家的意见。

vuex 的定位就是 “一个专为 Vue.js 应用程序开发的状态管理模式”，这个模式的意义就是串通 vue 各个组件之间的状态，这种功能时大型项目必需的，如果不把系统级的功能做到 vuex 里，将很难在整个工程的任何组件中调用。

例如 D2Admin 的侧边栏菜单的折叠状态，一般是由用户触发，但是假如你有一个特殊的页面需要尽可能地有大面积展示，这时候你只需要在页面组件中调用 vuex 中关闭侧边栏的方法就可以了。假如关闭侧边栏的方法只写在 layout 组件里，那我们就没有办法在其它地方任意调用了。像用户信息，全屏，搜索功能，尤其还有数据持久化这种在很多地方都要使用的东西，放在 vuex 里是最好的。

假如你不需要这些功能，其实大可不必留意，只关注你需要的地方就好。

已经将每个模块明明确拆分，没有很难的地方，你可以单独研究：

![](https://qiniucdn.fairyever.com/20181029202928.png)

**Comment by Aysnine** [comment]
@koy-tome  db 模块是将数据持久化到 localStorage 中，也就是浏览器为每个网站提供的存储空间，类似于 cookies，只要浏览器不清空缓存。

![image](https://user-images.githubusercontent.com/10137653/47775188-f9413d00-dd29-11e8-9f0a-e8a185765e6c.png)

**Comment by koy-tome** [comment]
'肥肠'感谢两位大佬的答疑, 现在真的理解vuex和这个db了.
