### ISSUE TITLE
🔩 功能开发 | 希望能有一套完善的权限解决方案

### ISSUE THREAD

**Issue by winter-ice** [d2-projects/d2-admin#122]
1. 权限节点可由后端定义。
2. 根据权限动态渲染菜单。
3. 根据权限动态生成路由。
4. 精确到页面小组件级别的权限。建议在全局有个自定义命令 例如 `v-can` ，在任何组件中使用该命令来确定该组件是否渲染。
5. 规范、简明、清晰的权限定义。简洁明了的权限数据格式。

来自一个PHPer，前端菜鸡的请求。感觉这套管理系统速度很快，而且界面也好看。但是一个没有权限方案的系统无法在项目中使用啊。一个后台系统权限模块是必备的吧_

**Comment by FairyEver** [comment]
中肯的建议，我们会考虑

**Comment by winter-ice** [comment]
看了很多开源的vue后台解决方案，例如 vue-element-admin、iview-admin等等，这些项目的权限方案感觉都并不是很好，缺点有：逻辑相对复杂，结构不是很清晰，没有考虑性能优化等。(当然也可能是因为我前端比较菜的原因)，d2-admin在我一个后端看来，代码结构、逻辑写的比较清晰，比较容易看懂，各种组件也很完善，但是就是缺少一套完善的权限解决方案。其他的开源项目那种前端配置权限的，有配置角色的，有在前端定义好权限节点的。这些方案其实并不符合实际开发场景，实际中权限肯定还是由后端来返回的，而且比较细粒度，不可能光定义角色就行的。

ps: 希望作者能把重点放在这种比较核心的功能上，具体demo，组件的开发等，可以把优先级调低一点，因为不同的项目对于页面中展示型的东西需求肯定不一样，大概率还是要自己重新写的。而这种核心功能是可以所有项目通用的 😄

**Comment by mojie126** [comment]
> 看了很多开源的vue后台解决方案，例如 vue-element-admin、iview-admin等等，这些项目的权限方案感觉都并不是很好，缺点有：逻辑相对复杂，结构不是很清晰，没有考虑性能优化等。(当然也可能是因为我前端比较菜的原因)，d2-admin在我一个后端看来，代码结构、逻辑写的比较清晰，比较容易看懂，各种组件也很完善，但是就是缺少一套完善的权限解决方案。其他的开源项目那种前端配置权限的，有配置角色的，有在前端定义好权限节点的。这些方案其实并不符合实际开发场景，实际中权限肯定还是由后端来返回的，而且比较细粒度，不可能光定义角色就行的。
> 
> ps: 希望作者能把重点放在这种比较核心的功能上，具体demo，组件的开发等，可以把优先级调低一点，因为不同的项目对于页面中展示型的东西需求肯定不一样，大概率还是要自己重新写的。而这种核心功能是可以所有项目通用的 😄

同感...在我一个后端看来，结构是比较清晰的...强烈支持将权限这块儿提到最高优先级...

**Comment by FairyEver** [comment]
@Aysnine @Jiiiiiin 我们有时间讨论一下吧，大家想想权限这方面应该怎么做

**Comment by yundGo** [comment]
PHP附议。。

**Comment by ZXCDFGTYU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    php的话auth或者rbac可以考虑下，这是比较通用的做法了。其他语言应该也有对应的实现。

    在2018年11月13日 16:42，云端<notifications@github.com> 写道： 


PHP附议。。

**Comment by winter-ice** [comment]
有最新动态么？

**Comment by myseed** [comment]
java也赞同。。。

**Comment by HydeSong** [comment]
强烈建议搞一套

**Comment by magicdvd** [comment]
后端返回权限控制，前端负责根据规则渲染菜单。
rbac 还是很宽泛的概念，到实际开发的时候，其实是路由的权限控制。
粗粒度 只关心 uri , 细粒度要关心请求的全部.
举个rest api 例子
```
/item/{id}

POST:  更新的权限
GET：读取的权限

RoleA:  { uri: /item/{id}, priv: [POST,GET]}
RoleB: {uri:/item/{id}. priv:[GET]}

```
但是这类权限定义太细了。。细的我都头大
所以还有种偷懒的想法，权限只和page相关，只要page能看，那么page内所有功能api都可用

Menu:  Page1, Page2

RoleA: {priv: [Page1,Page2]}
RoleB: {priv: [Page1]}

对应请求就需要额外改造，传递一个 source:来源Page的参数 ，使后端用来判断权限，当然用referrer也可以考虑。
```
我就随便说说，框架做的很ok， 文档还是有些缺失，我老年人了查起来慢 :(
强烈建议尽快加上权限管理。

**Comment by namklaw** [comment]
我目前用是权限树，一级节点，大部分类别是菜单，对应顶部的菜单；二级节点，对应左侧的菜单；三级节点可能是菜单类别，对应左侧菜单的子菜单，也可能是组件类别，对应的是该菜单对应的页面里的该组件是否显示，在往下可以是组件细化的配置类别。

**Comment by winter-ice** [comment]
> 我目前用是权限树，一级节点，大部分类别是菜单，对应顶部的菜单；二级节点，对应左侧的菜单；三级节点可能是菜单类别，对应左侧菜单的子菜单，也可能是组件类别，对应的是该菜单对应的页面里的该组件是否显示，在往下可以是组件细化的配置类别。
> 对于可能存在的不同用户需要相同功能，但对应组件的显示不同的情况不适用。【补丁：但可以通过当前页面增加身份信息接口，来增加参数来辨别组件的显示内容。】

我目前的权限节点结构跟你差不多，等D2出来权限方案，我可以根据前端再去调我后端的数据结构。。毕竟我改后端比改前端省事多了。。

**Comment by Jiiiiiin** [comment]
我这边下个月估计会有点眉目了，这个月先把后台rbac和前台逻辑写完

**Comment by Jiiiiiin** [comment]
@FairyEver @winter-ice https://github.com/Jiiiiiin/jiiiiiin-security#%E8%AE%A1%E5%88%92 快了 😃

**Comment by Jiiiiiin** [comment]
目前已经完成我预想的两点：
1. 前端页面可见性的权限校验（登录之后配置登录用户的后端授权资源集合）
2. 可见页面中某个组件（如下面的检索框）的可见性（或disable）的权限校验（使用指令）

![](https://ws3.sinaimg.cn/large/006tNbRwgy1fy9sw9umu8j316n0g13zv.jpg)

详见：https://github.com/Jiiiiiin/jiiiiiin-security/blob/master/jiiiiiin-client-manager/src/plugin/vue-viewplus/rbac.js

因为一个按钮，比如更新，在后端看来可能需要几个接口的支持，所以目前`v-access:url.[disable]="['admin', 'admin/*']"`中配置的是url，后期还会直接以**资源别名**的方式来标识一个资源（一组接口），这样对比的性能就会提升一些。

@FairyEver 老大可以看看先

**Comment by Jiiiiiin** [comment]
更新文档：[rabc模块](http://jiiiiiin.cn/vue-viewplus/#/rbac)

**Comment by FairyEver** [comment]
大家可以先参考 @Jiiiiiin 的项目

**Comment by Jiiiiiin** [comment]
@FairyEver 😃

**Comment by wjkang** [comment]
这是我写的一套解决方案[d2-admin-pm](https://github.com/wjkang/d2-admin-pm)

**Comment by winter-ice** [comment]
> 这是我写的一套解决方案[d2-admin-pm](https://github.com/wjkang/d2-admin-pm)

star了，掘金也收藏了，现在正在参考d2-crud改个符合自己的封装，还没细看，等我忙完再细看把，不过还是比较期待官方的实现

**Comment by sbilly** [comment]
@Jiiiiiin 可以看一下 https://github.com/casbin/casbin

**Comment by huyongyong1992** [comment]
frameIn里的路由可以有后端返回，通过vue-router的addRoute动态挂载路由。这种改动比较小就目前来说。

**Comment by itmeryn** [comment]
权限 
前端代码 http://git.itplus.cc/ryn/D2admin
后端代码 http://git.itplus.cc/ryn/flask-restful
有兴趣可以参考

**Comment by Fengmaybe** [comment]
做了两个项目，对于菜单权限都是后端直接返回一级菜单和二级菜单的权限值，比如返回permission=[‘a’, 'b', 'c'];
此时我在登陆成功后获取到这个permission数组想去和route.js的路由进行对比过滤。如下：
``` 
const frameIn = [  
  {  
    path: '/',  
    redirect: { name: 'index' },  
    component: layoutHeaderAside,
    meta:{
      auth: true,
      permission: 'a'
    },
    children: [
      // 首页
      {
        path: 'index',
        name: 'index',
        meta: {
          auth: true,  
          permission: 'b',  
        },  
        component: _import('system/index')  
      }],  
},
{
path: '/page',
name: 'pagedemo',
meta:{
  auth:true,
perrmission: 'd'
}
} 
``` 
此时过滤出来就是最后一个`/page`路由需要隐藏。
大致就是这样的一个过程。
请问在D2当中这样好不好实现呢？大致思路是什么？谢谢。

**Comment by wjkang** [comment]
@Fengmaybe 参考 https://github.com/wjkang/d2-admin-pm/blob/master/src/router/index.js，我的路由是后端返回的，你路由在前端的话，在addRoutes之前用权限值过滤一遍

**Comment by DionSun** [comment]
@itmeryn 你好，我无法注册那个网站，有其他的地址可以访问吗？ 我想学习下你的项目，感谢。

**Comment by GreenHatHG** [comment]
> 大家可以先参考 @Jiiiiiin 的项目
> 
> * [vue-viewplus](http://jiiiiiin.cn/vue-viewplus/#/)
> * [jiiiiiin-security](https://github.com/Jiiiiiin/jiiiiiin-security)

你好
[jiiiiiin-security](https://github.com/Jiiiiiin/jiiiiiin-security)
page 404了

**Comment by FairyEver** [comment]
> > 大家可以先参考@Jiiiiiin的项目
> > 
> > * [VUE-viewplus](http://jiiiiiin.cn/vue-viewplus/#/)
> > * [jiiiiiin安全](https://github.com/Jiiiiiin/jiiiiiin-security)
> 
> 你好
> [jiiiiiin-security](https://github.com/Jiiiiiin/jiiiiiin-security)
> 页面404了

我联系了一下作者，原因是被公司要求关闭了仓库，很棒的项目，应该是公司比较重视。

**Comment by itmeryn** [comment]
> @itmeryn 你好，我无法注册那个网站，有其他的地址可以访问吗？ 我想学习下你的项目，感谢。

http://git.itplus.cc/itplus/opsPlusFront

**Comment by FairyEver** [comment]
针对 D2Admin 1.x 权限改造的演示项目：https://github.com/d2-projects/d2-admin-cms-go
