### ISSUE TITLE
🤔 提问 | 如何仅关闭外部的滚动条，不关闭里面的滚动条

### ISSUE THREAD

**Issue by carolcoral** [d2-projects/d2-admin#126]
尝试过使用在 theme-base.scss中的 <code>.d2-theme-container-main-body</code> class里面新增
```
 ::-webkit-scrollbar {display:none}
```
这样可以实现隐藏滚动条，但是会发现不管是外部的滚动条，还是里面table的滚动条全部隐藏了
![](https://raw.githubusercontent.com/carolcoral/SaveImg/master/1.png)

但是我期望的效果是只隐藏外面的滚动条或者只隐藏里面table的滚动条，而不是同时隐藏和同时显示，谢谢

还有一个问题，如何设置图片中table范围的高度，没有找到可以固定高度的地方，发现用的是自动增加自适应的高度。
![](https://raw.githubusercontent.com/carolcoral/SaveImg/master/QQ%E6%88%AA%E5%9B%BE20181106113247.png)

**Comment by FairyEver** [comment]
外部滚动条隐藏试试参考 [https://d2admin.fairyever.com/#/demo/components/container/full-bs](https://d2admin.fairyever.com/#/demo/components/container/full-bs)

表格是 elementUI 的表格，如果没有 API 的话就需要你自己加样式修改了

**Comment by carolcoral** [comment]
@FairyEver 好的，谢谢了，层级太多了，找了好多层才找到对应的class。。。
