### ISSUE TITLE
🤔 提问 | 麻烦问一下如何在路由切换之后将页面滚动到页面的顶部

### ISSUE THREAD

**Issue by guygubaby** [d2-projects/d2-admin#127]
这些页面是在同一个router-view里面渲染的，就是有一些页面很长，需要滚动到很下面，然后一切换到另一个页面(router push)，滚动条还在上次的位置，导致显示错位了，这该怎么办，我看了项目的源码也没有找到在哪里设置的😭

**Comment by guygubaby** [comment]
求大佬赐教

**Comment by FairyEver** [comment]
意见：你可以试试通过 $el 属性获取容器 dom 节点，然后用原生js重新设置滚动位置，以上操作应该在 mounted 生命周期内。

**Comment by guygubaby** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢你~
    
        
            
        
    
    
        
            
        
    
    
    
    

    

    

    在2018年11月6日 17:17，李杨<notifications@github.com> 写道： 


意见：你可以试试通过 $el 属性获取容器 dom 节点，然后用原生js重新设置滚动位置，以上操作应该在 mounted 生命周期内。
