### ISSUE TITLE
🤔 提问 | 对所有请求设置的X-TOKEN的疑问

### ISSUE THREAD

**Issue by carolcoral** [d2-projects/d2-admin#128]
我看到在 /src/plugin/axios/index.js 里面这段代码可以设置所有的请求拦截
```
// 请求拦截器
service.interceptors.request.use(
  config => {
    // 在请求发送之前做一些处理
    if (!(/^https:\/\/|http:\/\//.test(config.url))) {
      const token = util.cookies.get('token')
      if (token && token !== 'undefined') {
        // 让每个请求携带token-- ['X-Token']为自定义key 请根据实际情况自行修改
        config.headers['X-Token'] = token
      }
    }
    return config
  },
  error => {
    // 发送失败
    console.log(error)
    Promise.reject(error)
  }
)
```

在这段代码里面设置了所有请求的header必须带有<code>X-Token</code>字段，但是当我在控制台的 <code>network</code>里面查找的</br>时候发现我的<code>request</code>里面并没有这个 <code>header</code>，请问这个是还需要在哪里设置吗</br>并且如果我需要设置所有请求都带上这个<code>header</code>应该怎么做，</br>是需要在请求地址上加上<code>headers=this.headers</code>的属性吗，谢谢

**Comment by carolcoral** [comment]
当我设置 <code>config.headers['X-Token'] = token</code> 中的 <code>X-Token</code> 为其他任意值的时候，其他所有页面均不能使用，因为做了拦截，但是没有找到该参数设置的位置

**Comment by rongxingsun** [comment]
这个是后台夸域问题

**Comment by FairyEver** [comment]
检查一下你们的后台允许了哪些 header 参数

**Comment by carolcoral** [comment]
@FairyEver 我后台设置的是USER_TOKEN，当我把X-TOKEN改成USER_TOKEN后点登录返回成功，但是页面不跳转，改成X-TOKEN就好了，没明白，我没有用mock数据
@rongxingsun 跨域应该是不存在的，我设置过了跨域，所以我登录功能等都可以成功，但是设置header中的X-TOKEN为USER_TOKEN后就不能跳转了

**Comment by FairyEver** [comment]
如果携带了后台不允许的 header 确实最后结果和跨域差不多，你应该使用后台设置的那个。至于页面不跳转的问题，你看一下你在登陆之后是不是向 cookie 里存入了有效的 token，页面跳转有一个根据 token 判断的拦截：

https://github.com/d2-projects/d2-admin/blob/0e891d2837ffe57c441ff43a5f1f439f8e154486/src/router/index.js#L26-L51

token 是在这里设置进去的

https://github.com/d2-projects/d2-admin/blob/0e891d2837ffe57c441ff43a5f1f439f8e154486/src/store/modules/d2admin/modules/account.js#L29-L35

有可能是你用的登陆接口不是在那个位置返回的 token ，导致没有保存到 cookie，最后验证失败，就会永远你在登陆页面。

关于这个问题在文档中的解释：[link](https://doc.d2admin.fairyever.com/zh/question/#%E6%97%A0%E6%B3%95%E8%B7%B3%E8%BD%AC%E8%B7%AF%E7%94%B1)

**Comment by carolcoral** [comment]
@FairyEver 谢谢，我确实是在 src/store/modules/d2admin/modules/account.js里面set了我需要的两个token的，然后在axios里面的拦截器里面再修改的x-token为我需要的user_token，然而当我修改后我点击登录提示都是成功，数据也响应了，但是并没有跳转页面的操作，但是当我增加一条x-token就可以跳转了，与此同时在 src/store/modules/d2admin/modules/account.js 里面项目原来的 token 依然是注释状态，全局搜索后并没有找到任何地方需要get这个header的token的位置，不清楚这是为什么

**Comment by FairyEver** [comment]
页面跳转和 axios 的拦截器应该没有关系，只要 cookie 里存有，就可以跳转。你再检查一下你的 cookie，有没有类似 `d2admin-1.5.9-token` 这样的值，然后检查 vue-router 的拦截器，看看是哪里没有通过。

**Comment by carolcoral** [comment]
@FairyEver 全面仔细检查过了，找到问题了，是在请求之前依然被拦截了，使用webstorm全局搜索的时候查询的是x-token，实际应该检查token字段，谢谢
