### ISSUE TITLE
🤔 提问 | 打包之后运行无法加载图标

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#130]
打包后正常运行，但是所有图标无法显示，控制台截图：

![](https://qiniucdn.fairyever.com/20181109132356.png)

**Comment by FairyEver** [comment]
你指的是什么图标？fontawesome？还是你自己的svg图标？

**Comment by leoyuuuuu** [comment]
fontawesome和站内跟箭头一在一个文件的所有图标

**Comment by leoyuuuuu** [comment]
就是element-ui的图标库和fontawesome没打包进去

**Comment by FairyEver** [comment]
我没有遇到过你这个问题，是不是改了什么 webpack 配置？或者你提供一个最小的问题复现示例项目。也可以试一下新下载一个 D2Admin 然后直接打包，看看图标能不能正确加载。

**Comment by leoyuuuuu** [comment]
Failed to load https://api.github.com/repos/FairyEver/d2-admin/releases/latest: Redirect from 'https://api.github.com/repos/FairyEver/d2-admin/releases/latest' to 'https://api.github.com/repositories/117360777/releases/latest' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.


请教下是不是以上错误引起的打包后图标不能显示

**Comment by leoyuuuuu** [comment]
昨天中午到晚上，今天上午也试了还是不行，能不能麻烦大神远程看一下，十分谢谢了

**Comment by FairyEver** [comment]
> Failed to load https://api.github.com/repos/FairyEver/d2-admin/releases/latest: Redirect from 'https://api.github.com/repos/FairyEver/d2-admin/releases/latest' to 'https://api.github.com/repositories/117360777/releases/latest' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
> 
> 请教下是不是以上错误引起的打包后图标不能显示

你写出来的这串问题是老版本 D2Admin 有的一个请求最新版本的接口，访问的是 github，这个接口你可以去掉。和你的问题没有关系。

**Comment by FairyEver** [comment]
> 昨天中午到晚上，今天上午也试了还是不行，能不能麻烦大神远程看一下，十分谢谢了

你下载这个项目 [https://github.com/d2-projects/d2-admin-start-kit](https://github.com/d2-projects/d2-admin-start-kit) 

依赖安装完之后直接打包，如果图标有问题，这是 D2Admin 的代码错误，我们肯定会修复。如果是你自己写的其它代码有问题，和此项目无关。
