### ISSUE TITLE
点击登录有时候无法跳转到指定页面问题

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#131]
login ({ dispatch }, {
      vm,
      username,
      password,
	  code,
      route = {
        name: 'links'
      }
    }) {
      // 开始请求登录接口
      AccountLogin({
        username,
        password,
		code,
      })

我在上面的代码出设置了links，点击登录成功后有时候可以跳转到links，有时候直接跳转到首页了，我现在想每次点击登录的时候都到links页面

**Comment by FairyEver** [comment]
如果按照你上面代码这样设置，应该是不会跳转到其它页面的，除非你在调用 login 的时候手动指定了其它的路由。

你说的跳转到首页的情况应该是没有经过这一步，刷新浏览器后的跳转默认是 index，判断 cookie 中 token 生效的话不会再次经过 vuex 中的 login 方法。

**Comment by FairyEver** [comment]
请你注意一下 issue 提交格式：

![](https://qiniucdn.fairyever.com/20181114103733.png)

这是全部你提交的 issue，唯一一个标题格式正确的还是我帮你改的：

![](https://qiniucdn.fairyever.com/20181114103825.png)

在提交的时候提供模板了为什么你就偏不遵守规则？

![](https://qiniucdn.fairyever.com/20181114103915.png)
![](https://qiniucdn.fairyever.com/20181114104005.png)

**Comment by leoyuuuuu** [comment]
> 如果按照你上面代码这样设置，应该是不会跳转到其它页面的，除非你在调用 login 的时候手动指定了其它的路由。
> 
> 你说的跳转到首页的情况应该是没有经过这一步，刷新浏览器后的跳转默认是 index，判断 cookie 中 token 生效的话不会再次经过 vuex 中的 login 方法。

那请教一下，应该怎么改呢？

**Comment by FairyEver** [comment]
我没有复现你的问题，并且根据你提供的信息，没有办法给你提供建议
