### ISSUE TITLE
👾 BUG | 头部菜单栏关闭引起的报错

### ISSUE THREAD

**Issue by dnyz520** [d2-projects/d2-admin#133]
1.打开一个页面,再打开一个页面,出现2个tab.
2.在不激活第一个页面的情况下关闭第一个页面.

解决方案:
src\layout\header-aside\components\tabs\index.vue
大概第23行,其中 :key="index" 改换成 ":key="index + page.name""

![tim 20181114145229](https://user-images.githubusercontent.com/29970288/48465176-f14ec600-e81c-11e8-97ea-6dae546cabeb.png)

![tim 20181114145023](https://user-images.githubusercontent.com/29970288/48465181-f4e24d00-e81c-11e8-9c0b-ee94d5cc51f6.png)

**Comment by FairyEver** [comment]
感谢反馈 今晚解决
