### ISSUE TITLE
🤔 提问 | 启动项目后，无法自动打开浏览器

### ISSUE THREAD

**Issue by q1cha0** [d2-projects/d2-admin#135]
执行```npm run dev```后可以正常启动项目，但是无法“自动”打开浏览器。
看了下 package.json 的配置是有```--open```的。

**Comment by q1cha0** [comment]
```npm run serve``````npm run start```两个命令和前面效果一样。
尝试将依赖``` @vue/cli-*```改为```3.0.1```也还是无法自动打开浏览器。

**Comment by FairyEver** [comment]
之前也有人反映这个问题，目前收到的反馈是有人可以打开有人确实不会自动打开，可能和电脑系统的环境有关。你可以试试用cli3新建一个项目，检查是否能自动打开浏览器？

**Comment by q1cha0** [comment]
> 之前也有人反映这个问题，目前收到的反馈是有人可以打开有人确实不会自动打开，可能和电脑系统的环境有关。你可以试试用cli3新建一个项目，检查是否能自动打开浏览器？

cli3 命令行生成的官方demo hello-word 启动后默认是不能自动打开浏览器的，但是在 ```package.json```的```scripts - serve```中加上```--open``` 后就可以自动打开了。（PS：可奇怪的是，另一个叫 **iview-admin** 的```git clone``` 后，使用的同样是 cli3【@vue/cli-service install 后是 3.0.1 版，其他几个`@vue/cli-***`版本也一样】，`npm run dev`启动后却可以自动打开浏览器。）

尝试将`@vue/cli-***`这几个包的版本重装成和上述两个ok的一致，能正常启动但不能 open。

使用诸如`npx vue-cli-service serve --open`、`npx vue-cli-service serve --open --port 8765`，能正常启动但不能 open。

上面是 Windows 10（版本号1803） 环境下的，安装 `@vue/cli`后，`vue --version` 后是 3.1.3，cli3 是安装成功的。

macOS（系统版本 Mojave 10.14.1） 下的环境也尝试了，情况和上面基本一样。

**Comment by q1cha0** [comment]
已解决。我们跟进去看了下，快速解决方法二选一：1）删除 `yarn.lock` 文件；2）`npm i yarn -g` 全局安装 `yarn` 环境。

**Comment by q1cha0** [comment]
【**不介意**启动项目后无法自动打开浏览器的**请忽略**此问题】
对于有 `npm` 而没有 `yarn` 环境的情况，目前 `yarn.lock` 文件会引起此 issue 所描述的问题。
如果使用 `npm` 目前还是占多数的话，建议作者可以将 `yarn.lock` 文件独立出来。
