### ISSUE TITLE
👾 BUG | 进度条无法加载完成

### ISSUE THREAD

**Issue by dnyz520** [d2-projects/d2-admin#138]
打开游览器窗口,输入
https://d2admin.fairyever.com/#/demo/playground/store/menu
待全部载入完成后,再在地址栏输入并访问
https://d2admin.fairyever.com/#/demo/playground/store/menu
这是进度条将失去作用

ps:代码修改前预留

**Comment by FairyEver** [comment]
我测试了并没有什么问题？

**Comment by dnyz520** [comment]
> 我测试了并没有什么问题？

注销的情况下试试
