### ISSUE TITLE
🖐 其它问题 | D2CRUD 一个组件接收多个参数

### ISSUE THREAD

**Issue by XYruoyu** [d2-projects/d2-admin#140]
d2 crud 里可不可以传入两个键

``` js
{
  title: '原户型图',
  key: 'preview',
  component: {
    name: 'my-img'
  }
}
```

现在是 key 对应一个值，场景是：我在自定义组件里，需要preview字段，也需要另一个字段的显示

**Comment by FairyEver** [comment]
@sunhaoxiang 你来说吧

**Comment by sunhaoxiang** [comment]
可以在自定义组件中通过props拿到传入的数据，也可以通过在自定义组件props定义scope属性来拿到本行所有的数据，参考示例：https://d2admin.fairyever.com/#/demo/d2-crud/demo25
