### ISSUE TITLE
🔩 功能开发 |d2 crud 传入两个字段

### ISSUE THREAD

**Issue by XYruoyu** [d2-projects/d2-admin#141]
d2 crud 里可不可以传入两个键
{
title: '原户型图',
key: 'preview',
component: {
name: 'my-img',

    }
现在是key对应一个值，场景是，我在自定义组件里，需要preview字段，，也需要另一个字段的显示

**Comment by FairyEver** [comment]
稍后 D2CRUD 作者会在 https://github.com/d2-projects/d2-admin/issues/140 回复你
