### ISSUE TITLE
🤔 提问 | 同组件不同参的路由打开多个标签页，异步请求获取数据时，多标签页内容会全部变为最新标签页数据

### ISSUE THREAD

**Issue by Mikasa33** [d2-projects/d2-admin#142]
打开第二个标签页，异步请求获取数据，第一个标签页的 data 数据不是该页面原数据，会全部更新为第二个标签页异步请求获取的数据。
未开启缓存，每次点击编辑打开新标签页都会异步获取数据。
请问这个问题应该如何解决？
或者也可以讲一下列表页点击编辑某条，不弹窗而是打开新标签页编辑的实现方案。（多次点击编辑会打开多个标签页而不是覆盖编辑页面内容）
十分感谢。

如下图：

![image](https://user-images.githubusercontent.com/29498153/49010928-b13dfa80-f1af-11e8-960d-3f4973117d73.png)

![image](https://user-images.githubusercontent.com/29498153/49010950-bb5ff900-f1af-11e8-8321-3a34a0552a60.png)

**Comment by Mikasa33** [comment]
我今天尝试在 edit 页面中再引入一个 form 组件，给组件一个 key ，这样每次切换都会重新获取数据，无法使用页面缓存。

目前理想的样子是：点击新增打开编辑页面填写内容，切换也可以缓存。点击编辑打开编辑页面修改内容，切换也可以缓存，并且多个编辑页面之间的数据可以独自区分开。

之前群里大佬说可以使用 vuex ，根据路由唯一 id 区分来展示各自内容。还有 d2admin 中的页面快照 demo ，我也看了看，但是觉得存储到 db 不太顺手，也可能是我技术菜。

其他办法暂时没有想到，目前改成了只打开一个编辑页面，点击新增或编辑会刷新该编辑页面内容。

如果有好的解决办法就好了，感谢回复。

**Comment by FairyEver** [comment]
我写了一个简单的示例放到了线上：https://d2admin.fairyever.com/#/demo/business/issues/142

![image](https://user-images.githubusercontent.com/19357920/49195531-74961d00-f3c2-11e8-8bf5-dfe4c055776b.png)

点击每行最后一列的编辑按钮可以进行编辑。

## 无缓存编辑

这个编辑页面会在每次打开时都会请求数据。

## 带缓存编辑 DB

这个编辑页面会使用数据持久化功能进行缓存结果，只有在来源页面为列表页时才会刷新数据，其它所有来源页面都会使用本地存储的数据恢复页面。

在每个页面右下角有查看源码按钮，可以在线查看源代码。

> 注意 该模块更新了，请覆盖你本地的旧文件，API 没有变。下次版本发布时我会再公告一次。https://github.com/d2-projects/d2-admin/blob/master/src/store/modules/d2admin/modules/db.js

希望对你有所帮助。

**Comment by Mikasa33** [comment]
十分感谢您提供的示例。
但是由于个人技术水平的原因，还是有一些不太懂的地方想问一下，希望可以给予一些提示。

带缓存编辑 DB 的示例中，

> 只有在来源页面为列表页时才会刷新数据，其它所有来源页面都会使用本地存储的数据恢复页面。

不知这里能否做到，只有第一次从列表页点击进入编辑页面才会刷新数据，其它情况都使用本地存储的数据恢复页面呢？（因为如果打开编辑页面，点击切换回列表页后，再次切换到编辑页面时，也会触发刷新数据。）

还有另外一个问题，如果 DB 缓存页面数据过多的话，如何清理比较好呢？不知能否可以监听到当前标签页是否关闭，如果关闭，清除该页面缓存的数据。（对浏览器的 localStorage 不是很了解，如果提出的问题很低端，请见谅。。）

提出这么多问题真的是很抱歉，如果不方便解答也没有关系，您提供的示例已经很大的帮助了我。

**Comment by FairyEver** [comment]
> 只有第一次从列表页点击进入编辑页面才会刷新数据，其它情况都使用本地存储的数据恢复页面

这种逻辑需要自己去设计，增加额外的标识和判断，例如在请求数据之前先尝试在持久化中恢复，如果成功恢复数据就不去再次请求。

> 如果 DB 缓存页面数据过多的话，如何清理比较好呢

有专门清除持久化存储的 API:

https://doc.d2admin.fairyever.com/zh/sys-vuex/db.html#db

根据使用的持久化方式对应使用。

> 能否可以监听到当前标签页是否关闭，如果关闭，清除该页面缓存的数据

目前没有标签页关闭的钩子，但是你可以尝试在这个页面的合适[生命周期](https://cn.vuejs.org/v2/api/#%E9%80%89%E9%A1%B9-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90)中手动删除当前页面的持久化。

**Comment by Mikasa33** [comment]
真的是非常感谢您！一下子就想通了，自己绕半天绕不过弯。。

**Comment by deenbyte** [comment]
你好，页面已经失效，请问有备份吗

**Comment by deenbyte** [comment]
> 我写了一个简单的示例放到了线上：https://d2admin.fairyever.com/#/demo/business/issues/142
> 
> ![image](https://user-images.githubusercontent.com/19357920/49195531-74961d00-f3c2-11e8-8bf5-dfe4c055776b.png)
> 
> 点击每行最后一列的编辑按钮可以进行编辑。
> 
> ## 无缓存编辑
> 这个编辑页面会在每次打开时都会请求数据。
> 
> ## 带缓存编辑 DB
> 这个编辑页面会使用数据持久化功能进行缓存结果，只有在来源页面为列表页时才会刷新数据，其它所有来源页面都会使用本地存储的数据恢复页面。
> 
> 在每个页面右下角有查看源码按钮，可以在线查看源代码。
> 
> > 注意 该模块更新了，请覆盖你本地的旧文件，API 没有变。下次版本发布时我会再公告一次。https://github.com/d2-projects/d2-admin/blob/master/src/store/modules/d2admin/modules/db.js
> 
> 希望对你有所帮助。

已经失效了，看不到源码。
