### ISSUE TITLE
👾 BUG | 网页宽度比较小时 顶部导航栏显示不全

### ISSUE THREAD

**Issue by rockPrince** [d2-projects/d2-admin#148]
需要手动调整窗口大小 左右滚动的图标才会显示

**Comment by FairyEver** [comment]
感谢反馈，稍后我检查一下

**Comment by FairyEver** [comment]
我不是很确定是否有我的朋友修改过代码，目前这个问题我复现不了，而且代码里写了初次判断的逻辑

https://github.com/d2-projects/d2-admin/blob/fbbc4e8602432c10554c08bc5bf4df41d64176a9/src/layout/header-aside/components/menu-header/index.vue#L109-L116
