### ISSUE TITLE
👾 BUG | 全屏失效

### ISSUE THREAD

**Issue by E00n** [d2-projects/d2-admin#149]
screenfull.js:98 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.

**Comment by FairyEver** [comment]
如何复现这个 bug？

**Comment by E00n** [comment]
测试了一下 大概是浏览器的问题 我用的
![image](https://user-images.githubusercontent.com/19679433/49716446-c5452a00-fc8e-11e8-9b68-771aa7ddf031.png)
Edge 还有别的版本的chrome 都正常

**Comment by see365** [comment]
升级了Google浏览器最新版本，报同样的错误。

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/releases/tag/1.6.10 fixed
