### ISSUE TITLE
🌈 显示优化 | tab 显示内容宽度变化问题

### ISSUE THREAD

**Issue by moonose** [d2-projects/d2-admin#150]
提个小需求，当鼠标移到tab上时，tab内容会往左边移动，右边显示出删除图标。当鼠标来回在不同tab之间游走切换时，其实对视觉来说这样的变化有点不舒服。能否让字体内容固定不移地？

同时，页面的显示不知道哪可以关闭页面载入动态效果，能否直接显示？

非常感谢！

**Comment by FairyEver** [comment]
我不是很确定是否有我的朋友修改过代码，目前这个问题我复现不了，而且代码里写了初次判断的逻辑

https://github.com/d2-projects/d2-admin/blob/fbbc4e8602432c10554c08bc5bf4df41d64176a9/src/layout/header-aside/components/menu-header/index.vue#L109-L116

**Comment by FairyEver** [comment]
tab 组件：http://element.eleme.io/#/zh-CN/component/tabs

页面载入动态效果：https://github.com/d2-projects/d2-admin/blob/master/src/store/modules/d2admin/modules/transition.js
