### ISSUE TITLE
其它问题 | 打包生成域名配置文件操作步骤

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#154]
1.npm install --save-dev generate-asset-webpack-plugin
2.const GenerateAssetPlugin = require('generate-asset-webpack-plugin');
const createServerConfig = function (compilation) {
  let cfgJson = { ApiUrl: compilation };
  return JSON.stringify(cfgJson);
}
3.//让打包的时候输入可配置的文件
//这段代码加在plugins:[]中
  new GenerateAssetPlugin({
        filename: 'serverconfig.json',
        fn: (compilation, cb) => {
            cb(null, createServerConfig(compilation));
        },
        extraFiles: []
    })
用了以上操作打包后在dist还是没生成配置文件
查了很多文档，试了很多次打包后都没有生成域名配置文件，请大神指教一下，谢谢

**Comment by FairyEver** [comment]
“打包生成域名配置文件操作步骤” 不明白你的需求是什么

**Comment by leoyuuuuu** [comment]
> “打包生成域名配置文件操作步骤” 不明白你的需求是什么

需求是我想生成一个域名配置文件，方便在打包后可以直接修改域名和端口等
