### ISSUE TITLE
👾 BUG | 月份显示错误

### ISSUE THREAD

**Issue by MungoWang** [d2-projects/d2-admin#155]
如图： 月份应该是 1，但实际显示为0

错误截图：
![image](https://user-images.githubusercontent.com/16010337/51013367-f621c300-159c-11e9-8b6d-b32138f9a993.png)

**Comment by rockPrince** [comment]
Date getMonth 返回值是 0（一月） 到 11（十二月） 之间的一个整数。:)

**Comment by FairyEver** [comment]
楼上正解。你可以看看 dayjs 的 api。
