### ISSUE TITLE
🔩 功能开发 | 请求接口数据时超过10秒后显示“请求超时”信息且不再请求接口

### ISSUE THREAD

**Issue by leoyuuuuu** [d2-projects/d2-admin#156]

**Comment by leoyuuuuu** [comment]
全局除了一个接口不会按照这个规则，其余接口都超过10秒后显示“请求超时”信息且不再请求接口，请教一下怎么实现

**Comment by FairyEver** [comment]
[https://github.com/axios/axios#request-config](https://github.com/axios/axios#request-config) 在你不需要有超时的接口请求时，附加一个足够大的 timeout 参数，覆盖默认设置

**Comment by leoyuuuuu** [comment]
> https://github.com/axios/axios#request-config 在你不需要有超时的接口请求时，附加一个足够大的 timeout 参数，覆盖默认设置

  baseURL: baseURLIp,
  timeout: 10000, // 请求超时时间
  withCredentials:true
})
我在以上设置了timeout，可是10秒后接口依然返回了数据

**Comment by bigbirdhzp** [comment]
参考链接：https://segmentfault.com/a/1190000015157929

重写response响应拦截器
