### ISSUE TITLE
🔩 功能开发 | 支持自定义页面不同参的路径不新打开 tab

### ISSUE THREAD

**Issue by FairyEver** [d2-projects/d2-admin#157]

**Comment by winter-ice** [comment]
看来是在偷偷看群里啊，我刚在群里问的，就自己提了这个issue 😄

**Comment by winter-ice** [comment]
目前有几个影响点：
1. 不同参的页面用的是同一个页面组件，然后打开多个tab，因为这几个tab用的是同一个页面组件，会导致数据互相影响，虽然可以通过watch来解决就是了。但是来回切换的话这样watch会有性能影响。
2. 是如果参数不同就打开新tab的话这样感觉使用一会儿就会打开一堆的tab，不便于使用

**Comment by FairyEver** [comment]
在最早的时候，区分 tab 页签唯一性的是路由的 name 属性。后来有人发现，这样做的话，没有办法不同的参数打开多个 tab 页，之后改成了 fullPath，就是现在这样。但是现在这样就出现了上面你说的那个问题，也是不太好。

所以需要做一个既不是 name，又不是 fullpath 的区分方式。

**Comment by edazh** [comment]
> 关于实现方式的考虑，可以支撑几种类型配置：name、path(无querystring)、fullpath、自定义函数获取。可以先配一个默认值，然后每个route可以用meta来配置个性值。
> 
> 不知道这样能否满足需求？

同意。我也遇到了这种需求，我的解决方案是：

1. 每个route用meta来配置个性值
2. 在路由全局守卫处判断此个性值，来决定是否打断新建tab的操作
 //排除的路由name不再打开新tab
```
  const excluded = to.meta.nest && from.meta.nest && to.matched[0].path === from.matched[0].path
  if (excluded) return
```

**Comment by Suley** [comment]
使用一会就打开一堆TAB是现在最烦恼的问题，辛苦解决下~

**Comment by junshaochen** [comment]
页面不同参数的路径打开新Tab 还会有个问题，就是Tab Title的问题，望同步处理。

**Comment by fmwww** [comment]
我是通过在meta里面增加一个single属性，然后在store的open方法里面判断这个参数，为true则判断name属性是否一致，否则就通过fullPath判断，从而达到不同参数打开同一个页面，至于tab标题用store去动态更新就好了

```
// routes.js
meta: {
  title: 'title',
  auth: true,
  single: true
}
```
```
// /src/store/modules/d2admin/modules/page.js
// 判断此页面是否已经打开 并且记录位置
let pageOpendIndex = 0
const pageOpend = opened.find((page, index) => {
  let same = false
  if (meta.single !== undefined && meta.single) {
    same = page.name === name
  } else {
    same = page.fullPath === fullPath
  }
  pageOpendIndex = same ? index : pageOpendIndex
  return same
})
```

**Comment by leeyoungae** [comment]
> 我是通过在meta里面增加一个single属性，然后在store的open方法里面判断这个参数，为true则判断name属性是否一致，否则就通过fullPath判断，从而达到不同参数打开同一个页面，至于tab标题用store去动态更新就好了
> 
> ```
> // routes.js
> meta: {
>   title: 'title',
>   auth: true,
>   single: true
> }
> ```
> 
> ```
> // /src/store/modules/d2admin/modules/page.js
> // 判断此页面是否已经打开 并且记录位置
> let pageOpendIndex = 0
> const pageOpend = opened.find((page, index) => {
>   let same = false
>   if (meta.single !== undefined && meta.single) {
>     same = page.name === name
>   } else {
>     same = page.fullPath === fullPath
>   }
>   pageOpendIndex = same ? index : pageOpendIndex
>   return same
> })
> ```

没有打开新tabs ,但请问后续，页面怎么获取这个没有打开新tabs的参数？？

**Comment by fmwww** [comment]
> > 我是通过在meta里面增加一个single属性，然后在store的open方法里面判断这个参数，为true则判断name属性是否一致，否则就通过fullPath判断，从而达到不同参数打开同一个页面，至于tab标题用store去动态更新就好了
> > ```
> > // routes.js
> > meta: {
> >   title: 'title',
> >   auth: true,
> >   single: true
> > }
> > ```
> > 
> > 
> > ```
> > // /src/store/modules/d2admin/modules/page.js
> > // 判断此页面是否已经打开 并且记录位置
> > let pageOpendIndex = 0
> > const pageOpend = opened.find((page, index) => {
> >   let same = false
> >   if (meta.single !== undefined && meta.single) {
> >     same = page.name === name
> >   } else {
> >     same = page.fullPath === fullPath
> >   }
> >   pageOpendIndex = same ? index : pageOpendIndex
> >   return same
> > })
> > ```
> 
> 没有打开新tabs ,但请问后续，页面怎么获取这个没有打开新tabs的参数？？

不知道你是要获取什么参数，如果是路由参数或者query参数，应该是和正常一样获取的

**Comment by wangjue666** [comment]
> 页面不同参数的路径打开新Tab 还会有个问题，就是Tab Title的问题，望同步处理。

https://github.com/d2-projects/d2-admin/pull/302 https://github.com/d2-projects/d2-admin/pull/303 就解决了上述问题 可以来试试看 @winter-ice  虽然不同参数路由还是新打开tab 但是代码方面是不需要切换data,组件都是独立的状态，可以精简一些逻辑:smile_cat:
