### ISSUE TITLE
👾 BUG | 首页输入框 在 输入法中文状态 下跟会存在严重bug

### ISSUE THREAD

**Issue by junjielu2018** [d2-projects/d2-admin#163]
👾 BUG | 首页输入框 在 输入法中文状态 下跟会存在严重bug
```
具体表现就是：无法输入内容，也无法删除内容，会跟随定时器，将内容重置到输入前的状态

**Comment by han-feng** [comment]
d2-admin 首页有输入框？ 你说的是登录页吗？

**Comment by FairyEver** [comment]
不知道你在说什么？能不能提供复现方式？最好gif

**Comment by FairyEver** [comment]
> 👾 BUG | 首页输入框 在 输入法中文状态 下跟会存在严重bug
> 
> ```
> 具体表现就是：无法输入内容，也无法删除内容，会跟随定时器，将内容重置到输入前的状态
> ```

首页好像确实没有输入框，你是指搜索功能吗？

**Comment by edazh** [comment]
是定时器更新读秒的时候，我也遇到了。我是用refs直接操作dom解决的。具体是：给要定时更新读秒文本的组件添加ref，然后在定时任务里使用ref拿到el更新text,或者使用直接查出DOM，操作文本

**Comment by FairyEver** [comment]
> 是定时器更新读秒的时候，我也遇到了。我是用refs直接操作dom解决的。具体是：给要定时更新读秒文本的组件添加ref，然后在定时任务里使用ref拿到el更新text,或者使用直接查出DOM，操作文本

有复现规律吗？

**Comment by edazh** [comment]
> > 是定时器更新读秒的时候，我也遇到了。我是用refs直接操作dom解决的。具体是：给要定时更新读秒文本的组件添加ref，然后在定时任务里使用ref拿到el更新text,或者使用直接查出DOM，操作文本
> 
> 有复现规律吗？

感谢回复！具体步骤有点多，并且不保证一定重现.并且我认为此BUG不是d2admin特有，初步估计为elementUI或者vue的BUG。
![image](https://user-images.githubusercontent.com/16481165/54328992-eaa95180-464a-11e9-886c-0c0f22fdcbb3.png)

以获取验证码读秒功能为例，步骤如下：

输入手机号获取验证码，此时会在定时任务中更新验证码按钮绑定的文本，并持续

确保此时在中文输入法状态下，在输入邮箱的地方打出某些文字但是不输出到邮箱input，就是**不敲空格输出文字**

等到读秒更新，会把刚才输入的带虚下划线的内容清空，此时按下shift或者回车，就有几率在定时器更新验证码按钮时，刷新掉input框中输入的任何内容

在我调试期间发现，在出现以上情况的时候，邮箱的v-model为空，并且失效。

**Comment by junjielu2018** [comment]
> 是定时器更新读秒的时候，我也遇到了。我是用refs直接操作dom解决的。具体是：给要定时更新读秒文本的组件添加ref，然后在定时任务里使用ref拿到el更新text,或者使用直接查出DOM，操作文本

感谢，问题解决了
