### ISSUE TITLE
🎮 示例相关 | 导出表格文件损坏

### ISSUE THREAD

**Issue by Zz1204** [d2-projects/d2-admin#164]
导出的表格xlsx文件损坏，无法打开；csv文件可以打开，但是数据错误

**Comment by FairyEver** [comment]
你是指的这个页面吗？https://d2admin.fairyever.com/#/demo/plugins/export/table

**Comment by Zz1204** [comment]
这个页面也有这个问题     https://d2admin.fairyever.com/#/demo/business/table/1

**Comment by FairyEver** [comment]
我测试了一下，这边没有什么问题。

![image](https://user-images.githubusercontent.com/19357920/54419449-6c2fdb00-4742-11e9-9c02-b574c5692952.png)

![image](https://user-images.githubusercontent.com/19357920/54419407-4c001c00-4742-11e9-9170-9fde76b36caa.png)

![image](https://user-images.githubusercontent.com/19357920/54419414-515d6680-4742-11e9-9515-5e16c78e2436.png)

**Comment by Zz1204** [comment]
![image](https://user-images.githubusercontent.com/34231460/54419658-0001a700-4743-11e9-900e-98e482159b74.png)
![image](https://user-images.githubusercontent.com/34231460/54419697-1445a400-4743-11e9-9c81-cef886ca200e.png)
![image](https://user-images.githubusercontent.com/34231460/54419713-1dcf0c00-4743-11e9-8596-c9b3ee107b13.png)
我这边还是不行，难道是excel的问题😅

**Comment by Zz1204** [comment]
可以把导入导出单独拿出来用吗

**Comment by Zz1204** [comment]
找到问题了
![image](https://user-images.githubusercontent.com/34231460/54422929-7eae1280-474a-11e9-841d-1cd8fb2b7629.png)

并且新建项目使用了 @d2-projects/vue-table-export 模块，实现了导入导出
谢谢👍
