### ISSUE TITLE
🤔 提问 | 左侧菜单

### ISSUE THREAD

**Issue by momtboy** [d2-projects/d2-admin#165]
为什么官方示例在刷新的时候可以保持左侧菜单的显示[官方](https://d2admin.fairyever.com/#/demo/components/index)，而Clone下来的代码运行起来以后，刷新左侧菜单就变为没有侧栏菜单状态呢？

**Comment by FairyEver** [comment]
你是指的这个示例吗？https://d2admin.fairyever.com/#/index
好像没有可以让侧边栏显示“官方”的地方？

**Comment by momtboy** [comment]
我意思是  [https://d2admin.fairyever.com/#/index](https://d2admin.fairyever.com/#/index)这个上面的侧边栏在刷新的时候不会丢失，但是clone下来的代码 本地运行，刷新就会丢失侧边栏菜单的展示

**Comment by FairyEver** [comment]
前阵子我有事在忙，验证了确实有这个问题，稍后处理

**Comment by FairyEver** [comment]
追加 https://github.com/d2-projects/d2-admin/commit/d007ae61b2fd3aee0d88e96f304f87fbd0e379f1

**Comment by ws2534075171** [comment]
当选择左侧菜单的某一个菜单，再去点击这个菜单下的编辑时跳转到对应的编辑页面，又没有 办法，让这个左侧选中的菜单仍然保持选中状态的样式
![image](https://user-images.githubusercontent.com/24306844/58144752-39deb480-7c82-11e9-81a6-d73b600ed8db.png)
