### ISSUE TITLE
👾 BUG | d2admin/log/add 不存在

### ISSUE THREAD

**Issue by liweitao92** [d2-projects/d2-admin#168]
>  应该是 d2admin/log/push b吧
![image](https://user-images.githubusercontent.com/30191996/55670685-25a14c80-58ba-11e9-82c2-3c3a65a6e5f0.png)

**Comment by FairyEver** [comment]
这里以前已经更新了，应该是你那边文档网页有缓存，尝试刷新一下文档的页面

https://doc.d2admin.fairyever.com/zh/sys-vuex/log.html#actions-push

**Comment by FairyEver** [comment]
谢谢指出，已经在 https://github.com/d2-projects/d2-admin/commit/195892346ca8beae0e575dd42f6ff62119277b3e 修正
