### ISSUE TITLE
👾 BUG | 顶栏菜单收起时屏幕小无法完全显示

### ISSUE THREAD

**Issue by lawlietwind** [d2-projects/d2-admin#169]
![image](https://user-images.githubusercontent.com/13810063/55709656-619ff300-5a1b-11e9-8b33-34513143a0f0.png)
官方demo中把界面拉窄（例如宽度720px）至出现左右滚动按钮，刷新一次，右边按钮滚动到底仍不会完全显示所有菜单，但是当窗口大小改变后便恢复正常。
这是在菜单少的情况要把界面拉窄来复现，当顶栏菜单过多时便不能滚动到底，即不能完全显示。

**Comment by luchaohai** [comment]
在layout/header-aside/menu-header/index.vue的mounted事件里面：
![image](https://user-images.githubusercontent.com/11420885/55843096-1693f600-5b69-11e9-85b2-1ad509f87e07.png)
develop分支已修复

**Comment by lawlietwind** [comment]
好的，非常感谢:)
