### ISSUE TITLE
axios请求出现options

### ISSUE THREAD

**Issue by southorange1228** [d2-projects/d2-admin#170]
在请求数据的时候，使用了devProxy配置 关闭了mock数据 请求的时候发现会出现一次options请求（不是post也会有一个options请求）
![image](https://user-images.githubusercontent.com/32590310/55793084-ad729b00-5af4-11e9-9f85-a0133974d616.png)
![image](https://user-images.githubusercontent.com/32590310/55793102-b499a900-5af4-11e9-83a8-d7aca3ebf7d6.png)
![image](https://user-images.githubusercontent.com/32590310/55793115-be231100-5af4-11e9-9e4a-66ac010b0722.png)

**Comment by luchaohai** [comment]
我了解的options请求是在跨域情况下，浏览器为验证目标服务器是否允许跨域请求而发起的，这和是否是get，还是post没有关联。你可以去了解一下CORS，“跨域资源共享”
