### ISSUE TITLE
🎮 示例相关 | heatmap 不显示

### ISSUE THREAD

**Issue by zhaobinhong** [d2-projects/d2-admin#171]
[地图热力图](https://d2admin.fairyever.com/#/demo/charts/list/heatmap/demo2)
![image](https://user-images.githubusercontent.com/14801442/56011407-0f601a00-5d1a-11e9-89fc-fa869e00bffd.png)

**Comment by FairyEver** [comment]
mock.js 会影chart的地图数据加载

参考 https://github.com/d2-projects/d2-admin/blob/master/src/views/demo/charts/list/map/demo1/index.vue 的解决办法，或者在你的项目中去掉 mock.js 相关的内容

**Comment by zhaobinhong** [comment]
ok
