### ISSUE TITLE
🤔 提问 | 是否后续提供非webpack打包的版本，如grunt打包。

### ISSUE THREAD

**Issue by linenlin01** [d2-projects/d2-admin#174]
是否后续提供非webpack打包的版本的组件。

webpack版本不便进行集成debug。
在development的环境（kit）下单个app.js输出达到4M。

**Comment by FairyEver** [comment]
没有这种计划，不过网上有不少这方面（加速build以及减小打包体积）的教程，最后可以做到把不常用的插件拆分出去避免每次都加载 [Link](https://www.baidu.com/s?ie=UTF-8&wd=vue-cli%20%E6%89%93%E5%8C%85%E4%BC%98%E5%8C%96)
