### ISSUE TITLE
🤔 提问 | 页面resize后v-charts是怎么自动调整大小的?

### ISSUE THREAD

**Issue by LiXunGuan** [d2-projects/d2-admin#175]
最近在学习d2-admin源代码，自己模仿d2-admin做了一个框架 。
引入了v-charts。发现页面resize后 图表 不能自动调整大小。在d2-admin却可以!
不知道d2-admin中页面resize后 图表 怎么自行调整大小的
目前调用v-echarts 的 resize方法 暂时解决了

**Comment by FairyEver** [comment]
比如这个页面 https://github.com/d2-projects/d2-admin/blob/master/src/views/demo/charts/list/histogram/demo1/index.vue

没有什么额外的设置

**Comment by FairyEver** [comment]
https://v-charts.js.org/#/props

![image](https://user-images.githubusercontent.com/19357920/56344054-10e48300-61ef-11e9-807a-3566ea66d19e.png)

**Comment by LiXunGuan** [comment]
非常感谢，可能我这种布局的原因。需要自行调用resize
![QQ图片20190418153515](https://user-images.githubusercontent.com/7980846/56344396-df1fec00-61ef-11e9-8ee1-7cdbd73ee65a.png)

**Comment by FairyEver** [comment]
你的项目看起来挺不错，看起来支持多窗口，路由没有和窗口联系是吗？开源了吗

**Comment by LiXunGuan** [comment]
支持多窗口、没有采用路由关联。商用项目，没有开源。
