### ISSUE TITLE
👾 BUG | 源码按钮错误

### ISSUE THREAD

**Issue by FairyEver** [d2-projects/d2-admin#178]
![image](https://user-images.githubusercontent.com/19357920/56910918-3ff7d000-6ade-11e9-80f1-af1a561fc5b4.png)

原因：

https://github.com/d2-projects/d2-admin/blob/354b348da7ee443ab7aaf2061218334bbe0b924f/src/components/d2-container/components/d2-source.vue#L25-L32

`components.default.__file` 在开发环境和生产环境值不一样。

参考：

![image](https://user-images.githubusercontent.com/19357920/56911109-bb598180-6ade-11e9-9812-4a35536dd0ee.png)

**Comment by Aysnine** [comment]
采用自定义loader，向 `.vue` 注入路径代码：
https://github.com/d2-projects/d2-advance/blob/master/tools/vue-filename-injector/README.md

**Comment by FairyEver** [comment]
目前可以参考 https://juejin.im/post/5ccdc6ac51882541aa5232a4
