### ISSUE TITLE
不知道是什么错误  不太懂前段 算是BUG吗

### ISSUE THREAD

**Issue by xiaoshitou981023** [d2-projects/d2-admin#179]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
👾 BUG | 你的标题
```

如果需要，在这里描述具体内容

![微信截图_20190502151110.png](https://i.loli.net/2019/05/02/5cca982384a4a.png)

**Comment by FairyEver** [comment]
![image](https://user-images.githubusercontent.com/19357920/57187546-4e514c00-6f23-11e9-899b-a46b833dd6c1.png)
这都是你 Chrome 浏览器上某个插件的报错
