### ISSUE TITLE
👾 BUG | 搜索页面中的滚动条不会出现

### ISSUE THREAD

**Issue by dnyz520** [d2-projects/d2-admin#182]
![TIM截图20190509102853](https://user-images.githubusercontent.com/29970288/57423187-87e8c680-7245-11e9-9e87-3d3c0892a4f8.png)

突然发现滚动条不会出现了,看了很多个版本都是一样.
包括换了多款游览器也是一样.

地址 https://d2admin.fairyever.com/#/index
环境 Chrome 版本 74.0.3729.131（正式版本） （64 位）

**Comment by FairyEver** [comment]
我也不知道为什么突然出现了这个问题，但是现在修复了
