### ISSUE TITLE
👾 BUG | EDITOR显示错误

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#184]
看图，应该内容的z-index都要调整一下：
![image](https://user-images.githubusercontent.com/23008915/57584832-7ee04980-7512-11e9-8223-7bf056b7231a.png)

**Comment by FairyEver** [comment]
刚有时间看了一下这个问题，这个遮盖应该不是 z-index 的事，应该是 container 的 overflow hidden 导致的，编辑器的弹出层没有 append 到 body 上，而是和编辑器在一个父容器内，导致被裁减。暂时还没想到有好的解决办法。

**Comment by wangjue666** [comment]
@penjay  这个问题在quill的仓库也有很多人在反馈 
https://github.com/quilljs/quill/issues/1100
https://github.com/quilljs/quill/issues/2616
https://github.com/quilljs/quill/issues/1994

看回复 quill的开发者并不打算修复这个错误
> A DOM node being able to confine a descendent node visually is a DOM thing so there's not much Quill can do here unfortunately.

不过有人修复了它l https://github.com/Vitris/quill/commit/9c74fc98107c57f3f7164633014e18f1c9c37c62

但是他为啥不提PR呀:no_mouth:
