### ISSUE TITLE
 🎮 示例相关 | firefox浏览器兼容

### ISSUE THREAD

**Issue by redheart47** [d2-projects/d2-admin#185]
最新版64位firefox浏览器查看官方demo的时候，左侧菜单点击没有任何反应，顶部的菜单打开后，在内容区域的菜单点击才能正常显示

**Comment by FairyEver** [comment]
在我的电脑上暂时还没有复现：

![Snip20190520_1](https://user-images.githubusercontent.com/19357920/57991440-85a62800-7ae1-11e9-90d6-ec481f56ae9a.png)

GIF:

![1](https://user-images.githubusercontent.com/19357920/57991453-a2426000-7ae1-11e9-93f5-0cc7d2b91f8b.gif)
