### ISSUE TITLE
🌈 显示优化 | Menu超出宽度时，需要刷新才出现左右移动按钮

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#192]
人为使浏览器只有半屏，第一次进入首页顶部MENU无左右移动按钮，需要手动刷新后才出来。
![image](https://user-images.githubusercontent.com/23008915/60383298-9dd67300-9aa1-11e9-9a00-b4a00d23c100.png)

刷新后：
![image](https://user-images.githubusercontent.com/23008915/60383341-f1e15780-9aa1-11e9-82ab-7d6f17ad8dd4.png)

**Comment by lawlietwind** [comment]
Duplicate of #169
