### ISSUE TITLE
🤔 提问 | D2mAdmin调用后端接口 返回：public/index.html页面

### ISSUE THREAD

**Issue by suosui** [d2-projects/d2-admin#194]
概述：D2mAdmin部署到服务器，调用后端接口，返回：public/index.html页面
环境： 1 本地：（1）windows10  （2）node 10 （3）nginx1.17
　　　 2 服务器：（1）ubuntu 16.4 （2）node 10（3）nginx1.17
具体实施：（1）本地环境（npm run start）没有问题。
　　　　　（2）部署到服务器上（npm run build）后出现了如标题描述问题的。返回状态码和本地测试环境一样。

**Comment by FairyEver** [comment]
服务器配置的问题，配置你的服务器容器不将接口处理为页面请求，这个问题和前端项目没有关系
