### ISSUE TITLE
🤔 提问 | 浏览器刷新后 页面组件size设置丢失

### ISSUE THREAD

**Issue by itmeryn** [d2-projects/d2-admin#198]
我全局默认size  small
![image](https://user-images.githubusercontent.com/18156931/60947370-f7049900-a322-11e9-83b9-ec833f018189.png)
刷新前
![image](https://user-images.githubusercontent.com/18156931/60947380-fe2ba700-a322-11e9-86c0-912ed73f1ef8.png)
刷新后
![image](https://user-images.githubusercontent.com/18156931/60947408-0f74b380-a323-11e9-89c0-65314e84f052.png)
small 没有渲染

**Comment by FairyEver** [comment]
清空localstorage

**Comment by itmeryn** [comment]
![image](https://user-images.githubusercontent.com/18156931/61016590-ba887a00-a3c2-11e9-9549-257b0b8fa2e3.png)
我尝试修改layout header-aside  components header-size  index.vue 
这个问题得到解决  我用的是简化版  不知道完整版是如何处理这个问题的

**Comment by FairyEver** [comment]
在 https://github.com/d2-projects/d2-admin/commit/13c3d74397e59761294d6052c107474e3ca344a2 解决
