### ISSUE TITLE
⚙ 功能升级 | 增加closeAndRefresh方法

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#199]
https://d2admin.fairyever.com/#/demo/business/issues/142
如DEMO，建议在page.js中增加closeAndRefresh方法，其主要逻辑：关闭当前表单tab，如果列表页仍然已经打开，则刷新列表页。否则，仅关闭当前表单tab。请问TODO这里要怎么刷新。。。。。。。谢谢
![image](https://user-images.githubusercontent.com/23008915/61040797-e9731000-a403-11e9-81ea-a71bd9a87cc0.png)

**Comment by Ljsxx** [comment]
1. 首先在状态管理 **page.js** 文件中找到 **add** 方法，这个方法用于打开一个新页面，我们在每次打开一个新页面之前添加一个字段 **backPath** 用于记录当前页面

![微信图片_20190828102507](https://user-images.githubusercontent.com/47034054/63821312-1dd46880-c97f-11e9-8104-67955917d9af.png)

2. 新增 **closeBack** 方法，这个方法和 **close** 方法类似，**close** 方法是找到并打开当前标签的左边一个标签，而 **closeBack** 方法用于找到并打开记录的 **backPath**
```js
    // 关闭当前页并返回
    closeBack ({ state, commit, dispatch }) {
      return new Promise(async resolve => {
        // 下个新的页面
        let newPage = state.opened[0]
        // 如果关闭的页面就是当前显示的页面
        // 去找一个新的页面
        let len = state.opened.length
        for (let i = 1; i < len; i++) {
          if (state.opened[i].fullPath === state.current) {
            // 返回到上一个记录的页面
            let page = state.opened[i]
            // 返回到上一个页面
            let pageObj = state.opened.find(item => item.fullPath === page.backPath) || null
            if (pageObj && pageObj.path) {
              newPage = pageObj
            }
            break
          }
        }
        // 找到这个页面在已经打开的数据里是第几个
        const index = state.opened.findIndex(page => page.fullPath === state.current)
        if (index >= 0) {
          // 如果这个页面是缓存的页面 将其在缓存设置中删除
          commit('keepAliveRemove', state.opened[index].name)
          // 更新数据 删除关闭的页面
          state.opened.splice(index, 1)
        }
        // 持久化
        await dispatch('opend2db')
        // 最后需要判断是否需要跳到首页
        const { name = '', params = {}, query = {} } = newPage
        let routerObj = {
          name,
          params,
          query
        }
        router.push(routerObj)
        // end
        resolve()
      })
    },
```

3. 在 **main.js** 中添加全局方法
```js
Vue.prototype.$closeMultiWindow = () => {
  store.dispatch('d2admin/page/closeBack')
}
```

4. 使用方法，直接在页面中调用 **this.$closeMultiWindow()** ，就能关闭当前也并返回

**Comment by penjay** [comment]
> 1. 首先在状态管理 **page.js** 文件中找到 **add** 方法，这个方法用于打开一个新页面，我们在每次打开一个新页面之前添加一个字段 **backPath** 用于记录当前页面
> 
> ![微信图片_20190828102507](https://user-images.githubusercontent.com/47034054/63821312-1dd46880-c97f-11e9-8104-67955917d9af.png)
> 
> 1. 新增 **closeBack** 方法，这个方法和 **close** 方法类似，**close** 方法是找到并打开当前标签的左边一个标签，而 **closeBack** 方法用于找到并打开记录的 **backPath**
> 
> ```js
> // 关闭当前页并返回
> closeBack ({ state, commit, dispatch }) {
>   return new Promise(async resolve => {
>     // 下个新的页面
>     let newPage = state.opened[0]
>     // 如果关闭的页面就是当前显示的页面
>     // 去找一个新的页面
>     let len = state.opened.length
>     for (let i = 1; i < len; i++) {
>       if (state.opened[i].fullPath === state.current) {
>         // 返回到上一个记录的页面
>         let page = state.opened[i]
>         // 返回到上一个页面
>         let pageObj = state.opened.find(item => item.fullPath === page.backPath) || null
>         if (pageObj && pageObj.path) {
>           newPage = pageObj
>         }
>         break
>       }
>     }
>     // 找到这个页面在已经打开的数据里是第几个
>     const index = state.opened.findIndex(page => page.fullPath === state.current)
>     if (index >= 0) {
>       // 如果这个页面是缓存的页面 将其在缓存设置中删除
>       commit('keepAliveRemove', state.opened[index].name)
>       // 更新数据 删除关闭的页面
>       state.opened.splice(index, 1)
>     }
>     // 持久化
>     await dispatch('opend2db')
>     // 最后需要判断是否需要跳到首页
>     const { name = '', params = {}, query = {} } = newPage
>     let routerObj = {
>       name,
>       params,
>       query
>     }
>     router.push(routerObj)
>     // end
>     resolve()
>   })
> }
> ```
> 
> 1. 在 **main.js** 中添加全局方法
> 
> ```js
> Vue.prototype.$closeMultiWindow = () => {
>   store.dispatch('d2admin/page/closeBack')
> }
> ```
> 
> 1. 使用方法，直接在页面中调用 **this.$closeMultiWindow()** ，就能关闭当前也并返回

谢谢

**Comment by penjay** [comment]
> 1. 首先在状态管理 **page.js** 文件中找到 **add** 方法，这个方法用于打开一个新页面，我们在每次打开一个新页面之前添加一个字段 **backPath** 用于记录当前页面
> 
> ![微信图片_20190828102507](https://user-images.githubusercontent.com/47034054/63821312-1dd46880-c97f-11e9-8104-67955917d9af.png)
> 
> 1. 新增 **closeBack** 方法，这个方法和 **close** 方法类似，**close** 方法是找到并打开当前标签的左边一个标签，而 **closeBack** 方法用于找到并打开记录的 **backPath**
> 
> ```js
> // 关闭当前页并返回
> closeBack ({ state, commit, dispatch }) {
>   return new Promise(async resolve => {
>     // 下个新的页面
>     let newPage = state.opened[0]
>     // 如果关闭的页面就是当前显示的页面
>     // 去找一个新的页面
>     let len = state.opened.length
>     for (let i = 1; i < len; i++) {
>       if (state.opened[i].fullPath === state.current) {
>         // 返回到上一个记录的页面
>         let page = state.opened[i]
>         // 返回到上一个页面
>         let pageObj = state.opened.find(item => item.fullPath === page.backPath) || null
>         if (pageObj && pageObj.path) {
>           newPage = pageObj
>         }
>         break
>       }
>     }
>     // 找到这个页面在已经打开的数据里是第几个
>     const index = state.opened.findIndex(page => page.fullPath === state.current)
>     if (index >= 0) {
>       // 如果这个页面是缓存的页面 将其在缓存设置中删除
>       commit('keepAliveRemove', state.opened[index].name)
>       // 更新数据 删除关闭的页面
>       state.opened.splice(index, 1)
>     }
>     // 持久化
>     await dispatch('opend2db')
>     // 最后需要判断是否需要跳到首页
>     const { name = '', params = {}, query = {} } = newPage
>     let routerObj = {
>       name,
>       params,
>       query
>     }
>     router.push(routerObj)
>     // end
>     resolve()
>   })
> }
> ```
> 
> 1. 在 **main.js** 中添加全局方法
> 
> ```js
> Vue.prototype.$closeMultiWindow = () => {
>   store.dispatch('d2admin/page/closeBack')
> }
> ```
> 
> 1. 使用方法，直接在页面中调用 **this.$closeMultiWindow()** ，就能关闭当前也并返回

请问有什么办法关闭并刷新呢？其实主要的是刷新动作，例如我的list页面是cache的，新增记录完成后，需要 close & back & refresh list。

**Comment by Ljsxx** [comment]
5.  在 **App.vue** 文件中添加状态 **isRouterAlive**，需要刷新时更改状态即可
![image](https://user-images.githubusercontent.com/47034054/64085306-813a0e00-cd64-11e9-83fd-d8395c395491.png)

**Comment by penjay** [comment]
后来我使用的方法是把它从keepalive移除掉，在open时重新加上。是不是跟你的方法差不多？因为只要不做增加和修改，平时是需要缓存的。

<img width="672" alt="image" src="https://user-images.githubusercontent.com/23008915/64085451-66b46480-cd65-11e9-8850-1a49839cbc2d.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/23008915/64085460-7764da80-cd65-11e9-8a61-cd782f285fe5.png">
<img width="308" alt="image" src="https://user-images.githubusercontent.com/23008915/64085467-8055ac00-cd65-11e9-9278-0cbf0b829d37.png">

**Comment by Ljsxx** [comment]
刷新缓存的方法有很多种的，如果只是刷新请求还可以用发布订阅，但是实际开发中一般不用缓存，因为会增加很多工作量🙃

**Comment by penjay** [comment]
> 刷新缓存的方法有很多种的，如果只是刷新请求还可以用发布订阅，但是实际开发中一般不用缓存，因为会增加很多工作量🙃

啊！！！我的方法和你的方法，感觉都不太好。有没有其他方案？按一般的布局，是
search form = search,reset
toolbar = add,delete
table 
footer

按照删除Keepalive缓存的方式，使用户进入页面刷新，这样我的searchForm里（例如下拉列表等数据全部要重新request)，有没有什么好办法只刷新table，难道真的要加个cookie，在list写一个activited / beforeRouterEnter?

**Comment by Ljsxx** [comment]
> > 刷新缓存的方法有很多种的，如果只是刷新请求还可以用发布订阅，但是实际开发中一般不用缓存，因为会增加很多工作量🙃
> 
> 啊！！！我的方法和你的方法，感觉都不太好。有没有其他方案？按一般的布局，是
> search form = search,reset
> toolbar = add,delete
> table
> footer
> 
> 按照删除Keepalive缓存的方式，使用户进入页面刷新，这样我的searchForm里（例如下拉列表等数据全部要重新request)，有没有什么好办法只刷新table，难道真的要加个cookie，在list写一个activited / beforeRouterEnter?

试试发布订阅？

**Comment by penjay** [comment]
(ーー゛)我去，果然可以！我不是前端，第一次vue，都不知道有这个。谢谢。

**Comment by penjay** [comment]
list:
![image](https://user-images.githubusercontent.com/23008915/64269221-1f4bf500-cf6c-11e9-870d-722c339243bb.png)


edit:
![image](https://user-images.githubusercontent.com/23008915/64269210-19eeaa80-cf6c-11e9-8c34-72d6623e5364.png)


main:
![image](https://user-images.githubusercontent.com/23008915/64269197-13f8c980-cf6c-11e9-8382-6ea20c019dcf.png)


现在这样已经可以达到我的预期了

**Comment by penjay** [comment]
不过还要再优化一下，因为这样全部打开的router都会刷新。可能在'change'这里想想办法。

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/releases/tag/v1.18.0

这个版本的修改可以解决刷新问题了
