### ISSUE TITLE
⚙ 功能升级 | BS滚动模式下，无法选中文字

### ISSUE THREAD

**Issue by kakaxiu** [d2-projects/d2-admin#200]

**Comment by FairyEver** [comment]
BS 模式的本质是激活了 better-scroll 这个插件来显示更优化的滚动效果，开启这个插件的同时，鼠标选中文字时的拖拽会被处理成鼠标在拖拽页面（类似移动端的手指拖拽），这是两个**互相冲突**的交互（这个问题就像在移动端如何直接选中页面文字），现在还没有发现 better-scroll 有相关的配置。

不能通过设置 [disablemouse](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#disablemouse) 实现鼠标效果，这样的话同时也会失去在 PC 端上其它的鼠标功能，例如点击。

https://github.com/d2-projects/d2-admin/blob/324515e698952c138bde417dae84af7af0541085/src/components/d2-container/components/mixins/bs.js#L27

点击是可以正常实现的。

如果很需要鼠标选中文字，建议不要开启 better-scroll。

**Comment by wangjue666** [comment]
@kakaxiu bs已提供阻止默认事件配置项配置项 [Better-scroll文档](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#preventdefaultexception)

containers 组件也可以接收betterScrollOptions参数 
```
 betterScrollOptions: {
      type: Object,
      required: false,
      default: () => ({})
 }
```

可以在dev版本试试看 https://github.com/d2-projects/d2-admin/commit/b785d92b2e0689ae69fdccfba77be4a3f50d0098
