### ISSUE TITLE
👾 BUG | 如果停留在首页刷新的话，之前打开的标签都会关掉（本地运行才会，线上demo没有问题）

### ISSUE THREAD

**Issue by kakaxiu** [d2-projects/d2-admin#201]
d2在本地跑发现一个小问题， 如果停留在首页刷新的话， 之前打开的标签都会关掉
研究了一番发现是store   d2admin/page/open  逻辑好像有点问题， 默认取state.opened: setting.page.opened来判断当前页面有没有打开过
如果是首页就判断打开过，然后加载setting.page.opened的内容（只有首页）
如果不是首页反而判断没有打开过，加载缓存数据（缓存加当前页面）

但是官方线上demo不会出现这种情况， 求解~

**Comment by CuteFakin** [comment]
同样遇到这个bug了

**Comment by FairyEver** [comment]
我抽时间看一下（大概明天），大家先继续手里的其它工作

**Comment by FairyEver** [comment]
我测试发现是在本地运行的时候，page 模块中的 open 先于 openedLoad 执行导致，已经在 https://github.com/d2-projects/d2-admin/commit/90ab1151a24f7736276b7fa220a57f8e39c25a79 更新解决方法
