### ISSUE TITLE
🔩 功能开发 | renren-fast后台管理前端功能 集成

### ISSUE THREAD

**Issue by wfucksky** [d2-projects/d2-admin#202]
renren-fast后台管理前端功能

**Comment by wfucksky** [comment]
https://github.com/renrenio/renren-fast-vue 这个是官方提供的前端。

**Comment by wfucksky** [comment]
https://www.renren.io/community/project 这个是介绍页

**Comment by FairyEver** [comment]
可以基于这个前端的适配自己改造对接 https://github.com/d2-projects/d2-admin-cms-go
