### ISSUE TITLE
👾 BUG | 升级element-ui 2.11.0 后顶部菜单报错

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#204]
重现步骤：
git clone  ..... d2-admin

ncu -u element-ui

npm install

npm run dev
鼠标mouseenter顶部菜单即报错：
![image](https://user-images.githubusercontent.com/23008915/61928216-595bcb80-afaa-11e9-9e3d-d242cd889c31.png)

**Comment by FairyEver** [comment]
是这个组件的问题 https://github.com/d2-projects/d2-admin/blob/master/src/layout/header-aside/components/components/menu-sub/index.vue 和 element 的新写法有冲突，事件递归了

我抽时间更新一下

**Comment by zysniu** [comment]
同样遇到此问题。。。

**Comment by FairyEver** [comment]
新版的 element el-submenu 会将 mouseenter 事件手动传递到父元素的 el 上
而在 d2admin 以前的写法中 el-submenu 的父组件是 d2-layout-header-aside-menu-sub，其 el 又正好等于 el-submenu，所以导致事件无限循环

此问题已在 https://github.com/d2-projects/d2-admin/releases/tag/1.7.2 修复
