### ISSUE TITLE
👾 BUG | 显示异常

### ISSUE THREAD

**Issue by errorone** [d2-projects/d2-admin#206]
![1564844376(1)](https://user-images.githubusercontent.com/5329729/62413624-9166ac80-b643-11e9-8457-77ed31dd1021.jpg)
修改为true后，使用弹窗组件，在弹出窗体拖动，显示异常
![1564844545(1)](https://user-images.githubusercontent.com/5329729/62413626-9297d980-b643-11e9-8f1c-40adf175e05c.jpg)
显示结果
![1564844631(1)](https://user-images.githubusercontent.com/5329729/62413628-93307000-b643-11e9-9d4e-98f5f7ec64e5.jpg)

**Comment by FairyEver** [comment]
试试给 dialog 组件加上 `:append-to-body="true"`

https://element.eleme.io/#/zh-CN/component/dialog

**Comment by FairyEver** [comment]
实在不行就关掉 betterscroll 吧，可能有些不兼容

**Comment by liimin** [comment]
同样的问题 加 :append-to-body="true" 无效
