### ISSUE TITLE
👾 BUG | 多开同一组件的Tab后，数据会同步

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#207]
例如：
https://d2.pub/d2-admin/preview/#/demo/business/issues/142/edit-cache-db/1
https://d2.pub/d2-admin/preview/#/demo/business/issues/142/edit-cache-db/2

修改其中一个的文本框，另一个也会变化。有什么好办法解决此问题？谢谢

**Comment by FairyEver** [comment]
参考一下 https://d2admin.fairyever.com/#/demo/playground/page-cache/params/1

**Comment by wangjue666** [comment]
链接打不开了呀 老哥

**Comment by FairyEver** [comment]
> 链接打不开了呀 老哥

部署变更，上面的链接已经更新成最新的

**Comment by wangjue666** [comment]
老哥 这样解决感觉有点难受呀， 如果说页面存在的 Tab radio Dialog 这样的组件很多的时候 都需要保存这些组件的数据呢 您有更好地解决方案吗？
