### ISSUE TITLE
👾 BUG | 脚手架搭建的简化版（1.7.2）菜单展示异常

### ISSUE THREAD

**Issue by wyWang1993** [d2-projects/d2-admin#209]
左侧菜单栏列出所有菜单，在点击二级菜单后，上级菜单会折叠起来

**Comment by FairyEver** [comment]
是由于空 path 的处理以前写在 render 中，导致每次重新渲染的时候随机 ID 不固定。现在已经改为在 store 中统一处理空 path 的问题。

**Comment by FairyEver** [comment]
追加修改 c1f766fc560dee9d3a0824a70bbd0f1c17bf20f4

**Comment by FairyEver** [comment]
简化版追加修改 https://github.com/d2-projects/d2-admin-start-kit/commit/c1f766fc560dee9d3a0824a70bbd0f1c17bf20f4

**Comment by FairyEver** [comment]
完整版修改

* https://github.com/d2-projects/d2-admin/commit/326d43a28ef676a64b0815c59dc99e6a9387cafd
