### ISSUE TITLE
👾 BUG | 多次点击标签出错

### ISSUE THREAD

**Issue by cosoc** [d2-projects/d2-admin#213]
多次点击标签会触发这个错误：

```
vue-router.esm.js:2008 Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated"}
```

这是我修改过的代码部分：

``` js
/**
 * @class pool
 * @description 保存 pool (候选池)
 * @param {Object} state vuex state
 * @param {Array} routes routes
 */
init (state, routes) {
  const pool = []
  const push = function (routes) {
    routes.forEach(route => {
       // 这里如果不能正确添加路由信息，不显示菜单标题
      if (route.children && route.children.length !== 0) {  // 多加了如果有子级但是不为空的情况
        push(route.children)
      } else {
        if (!route.hidden) {
          const { meta, name, path } = route
          pool.push({ meta, name, path })
        }
      }
    })
  }
  push(routes)
  state.pool = pool
}
```

**Comment by FairyEver** [comment]
兄弟 先不说别的 看看你的 issue 样子，太不讲究了：

![image](https://user-images.githubusercontent.com/19357920/63208808-62ecd500-c10b-11e9-82d9-c1cfc16e864b.png)

**Comment by FairyEver** [comment]
已经修改：

![image](https://user-images.githubusercontent.com/19357920/63208833-d55db500-c10b-11e9-8f80-4e088c89bd89.png)

好的 issue 书写有助于后人参考

**Comment by cosoc** [comment]
> 兄弟 先不说别的 看看你的 issue 样子，太不讲究了：
> 
> ![image](https://user-images.githubusercontent.com/19357920/63208808-62ecd500-c10b-11e9-82d9-c1cfc16e864b.png)

我这样添加了成功显示标题了，就是双击会包这个错误！兄弟帮帮

**Comment by FairyEver** [comment]
怎么复现你的问题？

你指的是双击这里吗：

![image](https://user-images.githubusercontent.com/19357920/63210218-45753680-c11e-11e9-884f-24e974acb0fd.png)

**Comment by FairyEver** [comment]
我多次点击动态添加的标签页没有报错。你可以在 https://d2admin.fairyever.com/#/demo/playground/add-routes/routes 点点试试

**Comment by cosoc** [comment]
此bug是1.7.1版本以下bug，是由于旧的组件element-u升级i造成的bug！作者在1.7.2中已经修复，建议同志们升级到最新。已经解决

**Comment by shuyanzi** [comment]
> 此bug是1.7.1版本以下bug，是由于旧的组件element-u升级i造成的bug！作者在1.7.2中已经修复，建议同志们升级到最新。已经解决.。还有一个问题交代，如果你升级了vue路由组件到v3.1.2。不是完全移除依赖重新下载的话，也会出现这个问题。

那怎么完全修复呢？vue-router更新了，还是有这个问题

**Comment by cosoc** [comment]
> 那怎么完全修复呢？vue-router更新了，还是有这个问题

以前我遇到是:我直接命令更新element-ui组件,接着就会报这个错.然后删除node_modules文件重新下载依赖就好了.
