### ISSUE TITLE
@d2-admin/filters-dayjs 导致无法打包

### ISSUE THREAD

**Issue by cosoc** [d2-projects/d2-admin#215]
当我移除根目录下
package-lock.json文件，重新下载依赖包时，就会出现如下错误！
只有恢复package-lock.json文件才能正确build。不知道作者是否能给出建议！
还有这个问题严重的就是，如果移除这个依赖！那么vue的配置文件端口配置不生效了，他会产生一个随机端口。但是当你访问这个端口，控制台一直报网络异常

```js

This dependency was not found:

* @d2-admin/filters-dayjs in ./src/main.js

To install it, you can run: npm install --save @d2-admin/filters-dayjs

```

**Comment by FairyEver** [comment]
[@d2-admin/filters-dayjs](https://www.npmjs.com/package/@d2-admin/filters-dayjs) 这个包是存在的，这部分没问题。

这个依赖和 “vue的配置文件端口配置” 一点关系都没有。这只是一个把 dayjs 的 api 转成 vue 过滤器的插件。

临时的解决办法：如果你没有用到这套过滤器，删掉以下代码：

https://github.com/d2-projects/d2-admin/blob/1946f70a51004aa8dac0821ca284f499267b07d2/src/main.js#L29

https://github.com/d2-projects/d2-admin/blob/1946f70a51004aa8dac0821ca284f499267b07d2/src/main.js#L46

https://github.com/d2-projects/d2-admin/blob/1946f70a51004aa8dac0821ca284f499267b07d2/package.json#L17

**Comment by FairyEver** [comment]
我删掉了这部分代码：https://github.com/d2-projects/d2-admin/commit/820df1f0da18052d5ed34aeabff20f78cb5ee721

关于把 dayjs 做成 vue 过滤器并且包装成插件，我以前也觉得有些没必要。实际上几乎用不到。

如果你真的需要这部分功能，自己将以前 [packages/filters-date/src](https://github.com/d2-projects/d2-admin/tree/1946f70a51004aa8dac0821ca284f499267b07d2/packages/filters-date/src) 下的文件手动注册进来就好。
