### ISSUE TITLE
🤔 提问 | 设置菜单 如果是动态路由匹配怎么办

### ISSUE THREAD

**Issue by Murphycx94** [d2-projects/d2-admin#217]
### routes 配置文件
```javascript
{
    path: 'work-statistics/:id?',
    name: 'work-statistics',
    meta: {
      title: '数据统计',
      auth: true
    },
    component: _import('work/statistics')
  }
```
### aside 配置文件
```javascript
[
  { title: '数据统计', path: '/work-statistics' }
]
```

这样写的话，如果没有id的情况下是可以正常显示的。
如果有id的话，menu的active高亮状态会没有

如果想让它active高亮的话怎么办？

**Comment by FairyEver** [comment]
默认这样的情况确实不能正确激活菜单的高亮，因为高亮是根据 fullPath 判断的，你要自己修改一下 https://github.com/d2-projects/d2-admin/blob/master/src/layout/header-aside/components/menu-side/index.js 中给 menu 组件 defaultActive 参数对应的值的获取方式，比如加一层判断如果 menu 的path 和当前 $route.fullPath 可以关联，手动设置 defaultActive 参数值为当前的 $route.fullPath
