### ISSUE TITLE
建议集成 WebSocket

### ISSUE THREAD

**Issue by Aysnine** [d2-projects/d2-admin#22]
建议集成 WebSocket，在这之前我使用 [VueSocket](https://github.com/MetinSeylan/Vue-Socket.io) 可行，并有以下想法：
1. 只配置端口，默认与 http 访问同 host
2. 完整的默认事件，如：["connect", "error", "disconnect", "reconnect", "reconnect_attempt", "reconnecting", "reconnect_error", "reconnect_failed", "connect_error", "connect_timeout", "connecting", "ping", "pong"]
3. 对socket重连的配置，如重连尝试次数

**Comment by FairyEver** [comment]
mock.js 应该做不了这件事

**Comment by FairyEver** [comment]
暂时先不加这个功能了，先做其他事 : )
