### ISSUE TITLE
👾 BUG |  build 时 UglifyJs 不支持 es6问题

### ISSUE THREAD

**Issue by 857476491** [d2-projects/d2-admin#220]
![image](https://user-images.githubusercontent.com/23392017/63826147-4dd83780-c990-11e9-8c42-2892e5739904.png)

**Comment by FairyEver** [comment]
UglifyJs 本来就不支持 ES6

**Comment by FairyEver** [comment]
如果你添加的依赖有没有转码就发布的，就会有这个错误。

解决方式

* 去掉 UglifyJs
* 设置 UglifyJs 忽略的依赖
* 有其它的库可以让 UglifyJs 支持 ES6
