### ISSUE TITLE
👾 BUG | 左侧菜单选中偶发性问题

### ISSUE THREAD

**Issue by penjay** [d2-projects/d2-admin#221]
![image](https://user-images.githubusercontent.com/23008915/63906243-cea73a00-ca49-11e9-97e9-bf7f679317c5.png)

![image](https://user-images.githubusercontent.com/23008915/63906287-f9918e00-ca49-11e9-9137-aef007dc8b06.png)

DEMO测试站点也是一样，有时候刷新一次再点又可以选中   active了。

**Comment by xiaoxiaoxiaodouzi** [comment]
请问最后是如何处理的，我现在也有这个问题

**Comment by FairyEver** [comment]
侧边栏菜单和顶栏菜单已经重写过
