### ISSUE TITLE
🖐 其它问题 | 验证没有权限后，如何在本页跳转

### ISSUE THREAD

**Issue by netzhouxiang** [d2-projects/d2-admin#224]
项目快做完了，加权限过程中发现问题，我通过导航打开一个页面后，请求查询列表接口，接口没有权限；跳转无权限页面的问题！

现在的前置是：
1.路由有配置把B页面的tab标签隐藏
2.在axios公共返回处，验证无权限后，进行的统一跳转
3.A页面有开启页面缓存

我现在的想要实现的是：
在点击菜单后，第一次打开A页面，然后加成完成，执行异步查询列表方法，验证没有权限后，跳转到无权限提示的B页面，再次切换回来，还是显示的B页面
现在问题如下：
再次切换回来会显示A页面，因为tab标签里的路径是这个，但是A页面并不会再次执行加载完成方法了，因为有开启页面缓存

无权限提示的B页面：指“抱歉，您没有权限访问该页面”的一个正常页面

各种办法都想了，改一下tab就感觉错乱了

**Comment by FairyEver** [comment]
即使页面组件被缓存，你可以使用它的 activated 生命周期

https://cn.vuejs.org/v2/api/#keep-alive

**Comment by netzhouxiang** [comment]
> 即使页面组件被缓存，你可以使用它的 activated 生命周期
> 
> https://cn.vuejs.org/v2/api/#keep-alive

我用activated 没有用，  我现在的目的不是刷新接口

**Comment by FairyEver** [comment]
> "再次切换回来会显示A页面，因为tab标签里的路径是这个，**但是A页面并不会再次执行加载完成方法了**，因为有开启页面缓存"

解决的是你这个问题，所以说在 activated 生命周期处理
