### ISSUE TITLE
🔩 功能开发 | Element UI 组件国际化

### ISSUE THREAD

**Issue by zxy12666** [d2-projects/d2-admin#227]
我在项目中加入element-ui的国际化文件但是这并没有效果，能否提供有关element-ui组件的国际化示例？

**Comment by FairyEver** [comment]
代码已更新

* b8f5083113c1fa3e7e3230a53c1de25120a92826
* 5b5d164db33fde71152460415c2486f79b4cd4a0

![image](https://user-images.githubusercontent.com/19357920/65580599-904f5d00-dfac-11e9-8b89-108f7e0e3fd4.png)

![image](https://user-images.githubusercontent.com/19357920/65580613-96453e00-dfac-11e9-99ed-01d32f3909f1.png)

现在更改语言将同步影响 element 组件的国际化
