### ISSUE TITLE
🤔 提问 | 左侧二级菜单无法点击，只能展开，但是展开没东西

### ISSUE THREAD

**Issue by loongw513029** [d2-projects/d2-admin#230]
我后台生成的菜单最后一级的children为null，我已经处理了delete children为null的节点，显示在页面上如题，只能展开但是并没有东西，我想请教一下，这里关键点在什么地方

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/blob/511527ca24ec71dd8e23c830c65b4d279e85092d/src/menu/modules/demo-business.js#L1-L22

检查一下你的菜单数据结构是这样的吗
