### ISSUE TITLE
👾 BUG | 使用better-scroll会导致position: fixed失效

### ISSUE THREAD

**Issue by wupopo** [d2-projects/d2-admin#234]
查了下是因为 better-scroll 中标签含有 transform 这个属性。
better-scroll 和 position: fixed 不可兼得啊。
当然这个问题不属于 d2 带来的，只是提醒下其他小伙伴慎用哟。

**Comment by Sky9th** [comment]
我也遇到类似的问题了，使用了better-scroll ,el-dialog弹出层只要拖拽任何东西都会导致弹出层缩到内层

**Comment by FairyEver** [comment]
涉及弹出层组件的页面尽量不要用 better-scroll 了，以后的版本也计划废弃 better-scroll 改用其他滚动优化插件
