### ISSUE TITLE
🖐 其它问题 | 路由和菜单中的title如果国际化

### ISSUE THREAD

**Issue by cosoc** [d2-projects/d2-admin#237]
如题

**Comment by cosoc** [comment]
i18n你如何写

**Comment by FairyEver** [comment]
演示项目的菜单是前端写固定的，如果你项目也是这种方式，可以把每个菜单项目的 title 写成类似 sys.menu.aaa 的形式，然后在调用 asideSet 之前，先用 $t 处理一遍每个菜单的 title。同时在每次切换语言的时候重复此步骤。

如果你的项目菜单是后台返回的，可以给你们的后端接口增加 lang 属性，通过不同的语言参数让后端返回不同语言的菜单。

**Comment by FairyEver** [comment]
i18n 的配置你可以手动写，也可以在每个页面 vue 文件中设置这个页面在不同语言下的标题，类似：

``` js
export default {
  title: {
  	en: '',
  	ja: '',
  	zh: ''
	}
}
```

然后批量注册到 i18n 配置里

**Comment by FairyEver** [comment]
以上都是可以尝试的思路，具体的还是得你自己写

**Comment by cosoc** [comment]
> 以上都是可以尝试的思路，具体的还是得你自己写

我现在可以拿到所有菜单和路由,我i18n如何处理,  每个 title都是  sys.menu.aaa 的形式  
下面是代码


``js
// 引入
import i18n from '@/i18n'

  let allMenuAside = [...menuAside, ...leftMenu]
  let allMenuHeader = [...menuHeader, ...topMenu]
  allMenuAside.forEach(element => {
       if(element.title){
          element.title = ??? (i18n如何写表达式,这个不是很熟悉)
        }
     
``
