### ISSUE TITLE
👾 BUG | transition更改没有效果

### ISSUE THREAD

**Issue by djkloop** [d2-projects/d2-admin#238]
```
transition更改没有效果
```
第一次我关闭了动画效果（因为默认是开启的）
```
步骤：
（尝试直接更改setting.js里面的transition.active，但是没有效果，然后按照下面的步骤才更改成功）
1. 先在setting.js里面修改transition.active:false，
   然后在localStorage清除掉数据， 重新登陆才能更改成功
```
第一次关闭的设置之后重新更改为true
![image](https://user-images.githubusercontent.com/21050914/67747229-4225f180-fa63-11e9-8b03-58d585a13a58.png)
但是在layout里面打印this.transitionActive还是false，并没有更新
![image](https://user-images.githubusercontent.com/21050914/67747250-48b46900-fa63-11e9-951a-e75b4b279cf0.png)

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/blob/master/src/setting.js 这里面的设置都是作为默认值的，默认值是在 localStorage 中没有数据时才生效，如果在开发的时候需要更改，就必须要清空 localStorage。

如果希望用户使用的时候自动生效，需要修改版本号，例如将 `1.0.0` 修改为 `1.0.1`。用户再访问的时候以前的设置就会自动失效。原理见：https://fairyever.com/d2-admin/doc/zh/sys-util/#util-cookies-set

**Comment by djkloop** [comment]
@FairyEver 好的谢谢回复，
