### ISSUE TITLE
🌈 显示优化 | 侧边栏收起展开时卡顿的问题

### ISSUE THREAD

**Issue by YuArtian** [d2-projects/d2-admin#240]
emmmmm 如图：
![Kapture 2019-11-07 at 17 48 07](https://user-images.githubusercontent.com/16103819/68379179-5adf8700-0188-11ea-8a38-cd121f391eeb.gif)

**Comment by zhaojianxin1234** [comment]
把element menu组件的动画关了

collapse-transition --> false

**Comment by FairyEver** [comment]
因为侧边栏折叠会让右侧重绘，所以右侧内容越多其实看起来越卡，关闭 collapse-transition 确实是个办法缓解
