### ISSUE TITLE
🌈 显示优化 | 增强配色对比

### ISSUE THREAD

**Issue by qinyou** [d2-projects/d2-admin#243]
ElementUI 本身颜色 偏浅，  弹窗中的表单 感觉 颜色更浅了。
如果电脑 分辨率高 屏幕小 或  开屏蔽蓝光软件  ，真是要看瞎眼了。
（普通Windows笔记本）

**Comment by FairyEver** [comment]
默认主题的颜色配置 [src/assets/style/theme/d2/setting.scss](https://github.com/d2-projects/d2-admin/blob/master/src/assets/style/theme/d2/setting.scss)
