### ISSUE TITLE
👾 BUG | mockjs低版本导致的responseType失效

### ISSUE THREAD

**Issue by YuArtian** [d2-projects/d2-admin#244]
默认依赖的 mockjs 版本过低
自己实现Excel到处功能时 会有bug
相关issue [mockjs](https://github.com/PanJiaChen/vue-element-admin/issues/1778)
默认依赖的mock版本 `"mockjs": "^1.0.1-beta3",`

建议升到4.0以上
或者直接去掉mock功能吧
我写了篇文章讲解导出功能的问题 希望后来的人不要采坑了
https://zhuanlan.zhihu.com/p/69351824
https://juejin.im/post/5d884174e51d453b8b5fa6ba

**Comment by FairyEver** [comment]
添加 responseType 的复制：https://github.com/d2-projects/d2-admin/commit/090f70e5ee1074ad4fa0232212da596818a170fd
