### ISSUE TITLE
🔩 功能开发 | 是否考虑支持鼠标左/右滚动来移动已打开的选项卡功能？

### ISSUE THREAD

**Issue by lampo1024** [d2-projects/d2-admin#247]
如题，目前已打开的选项卡太多(超过了一屏)，只能点击左侧或者右侧的按钮来移动选项卡，让其出现在可视区域。如图：

![d2-admin](https://user-images.githubusercontent.com/3262079/69476217-2b7c7b80-0e12-11ea-915e-81169686e041.png)

是否考虑增加支持鼠标左/右滚动来移动已打开的选项卡功能？

**Comment by FairyEver** [comment]
这个 tab 组件是 element 自带的 tab 修改样式做出来的。参考：https://element.eleme.io/#/zh-CN/component/tabs。默认超出范围就是左右显示按钮。

如果使用鼠标左/右滚动的方式，在 macOS 上还好，如果在 Windows 上默认的滚动条始终显示会很难看。

PS：

不仅仅 tabs，上面顶栏菜单其实也是这样的逻辑，顶栏菜单的超出范围左右移动是自己写的，你可以这样修改：

修改 https://github.com/d2-projects/d2-admin/blob/master/src/layout/header-aside/components/tabs/index.vue，不使用原生的 overflow 效果，使用 betterscroll 或者 element 自带的 el-scrollbar 组件来美化滚动条。
