### ISSUE TITLE
👾 BUG | 登录跳转首页时，menu-header组件的load事件没有触发

### ISSUE THREAD

**Issue by xiao-xiaozi** [d2-projects/d2-admin#250]
版本：d2-admin-1.7.2

若菜单的宽度超过需要显示滚动时，在登录进入首页的时候，menu-header组件mounted函数下的load事件没有执行。导致checkScroll事件的计算是否显示滚动也没有执行。最后菜单没显示控制滚动的左右按钮。此时再次刷新页面load事件执行，菜单显示左右滚动按钮。

这样就限制了必须再刷新一次才可以滚动菜单。
我尝试将load去掉，直接在mounted里面执行checkScroll事件，发现可行。
不知这样是否会存在问题，望大佬斧正。

```
    // 初始化判断
    // 默认判断父元素和子元素的大小，以确定初始情况是否显示滚动
    // window.addEventListener('load', this.checkScroll)
    // 修改代码
    this.checkScroll()
    // 全局窗口变化监听，判断父元素和子元素的大小，从而控制isScroll的开关
    this.throttledCheckScroll = throttle(this.checkScroll, 300)
    window.addEventListener('resize', this.throttledCheckScroll)
```

**Comment by zhuangxiaohui** [comment]
我是在这个后面加个延迟触发
`  // 初始化延迟以确定初始情况是否显示滚动
    setTimeout(() => {
      this.checkScroll()
    }, 500)`

**Comment by wangjue666** [comment]
@xiao-xiaozi  已修复  https://github.com/d2-projects/d2-admin/commit/93d4267567a02eeb28f86c8612c0d645ccd853f1 
原因在于 组件mounted钩子执行时 页面已经onload 导致初始化滚动校验不成功
