### ISSUE TITLE
🤔 提问 | 发生代码错误时会浏览器卡死

### ISSUE THREAD

**Issue by iwangshuai888** [d2-projects/d2-admin#251]
在遇到异常的情况的时候整个浏览器都会卡死，然后杀死浏览器进程重新打开才会好，这是什么情况

**Comment by FairyEver** [comment]
框架本身没有这种问题的，你可以克隆 https://github.com/d2-projects/d2-admin.git 什么都不修改，本地 run 一下，你说的浏览器卡死可能是有死循环了（例如路由钩子里判断没权限然后跳转再进钩子又没有权限无线循环）。

**Comment by iwangshuai888** [comment]
正常运行的时候没问题，就是当我代码逻辑上出现错误的时候就会出现浏览器卡死，然后内存使用率飙升。

**Comment by FairyEver** [comment]
尝试关闭这个插件 https://github.com/d2-projects/d2-admin/blob/master/src/plugin/error/index.js 试试，因为自带一个错误捕捉，当你发生错误的时候会进入一个记录错误的逻辑，如果这个逻辑中再发生错误，就会一直循环了
