### ISSUE TITLE
切换标签再切回来,页面别销毁,无法保持页面内容!

### ISSUE THREAD

**Issue by cosoc** [d2-projects/d2-admin#253]
例如打开多个标签,点击切回其他标签再切回来页面被销毁重新生成了.有什么方法页面让现场保留

**Comment by charliezzo** [comment]
据说是 keep alive

**Comment by FairyEver** [comment]
* 文档参考 [https://d2.pub/zh/doc/d2-admin/pages](https://d2.pub/zh/doc/d2-admin/pages/#%E9%A1%B5%E9%9D%A2%E7%BC%93%E5%AD%98)
* 示例 [https://d2.pub/d2-admin/preview/#/demo/playground/page-cache/on](https://d2.pub/d2-admin/preview/#/demo/playground/page-cache/on)

示例页面右下角有查看源码按钮
