### ISSUE TITLE
🤔 提问 | menu的权限控制能做吗？

### ISSUE THREAD

**Issue by iYefeng** [d2-projects/d2-admin#255]
后台有角色划分，前端根据角色将部分页面隐藏，这个具体怎么实现好？

**Comment by FairyEver** [comment]
完整的角色+用户权限管理：https://github.com/d2-projects/d2-admin-cms-go

账号暂不开放，可以随便查看代码

**Comment by FairyEver** [comment]
动态菜单和权限的核心逻辑：

* https://github.com/d2-projects/d2-admin-cms-go/blob/master/src/router/index.js
* https://github.com/d2-projects/d2-admin-cms-go/blob/master/src/permission.js
