### ISSUE TITLE
🤔 提问 | 关于菜单栏

### ISSUE THREAD

**Issue by testyt24** [d2-projects/d2-admin#256]
我可以不适用框架的左侧和顶部菜单栏吗？ 
  详细情况就是整个页面只显示 d2-container 的内容 
![1578657189(1)](https://user-images.githubusercontent.com/36119272/72151337-e96bc100-33e2-11ea-87ea-75d16774165b.png)

**Comment by FairyEver** [comment]
在 layout 文件夹下新建一个 layout，和 https://github.com/d2-projects/d2-admin/tree/master/src/layout/header-aside 平级，然后注册路由时注册在这个 layout 下面就可以。如果全部都不需要侧边栏什么的，可以直接修改 header-aside layout
