### ISSUE TITLE
当多标签时，左侧的菜单栏联动激活失效

### ISSUE THREAD

**Issue by lytdev** [d2-projects/d2-admin#258]
![微信截图_20200210005640](https://user-images.githubusercontent.com/13446746/74106293-6e8ff480-4ba0-11ea-9c39-ec2c9c1e6091.png)

**Comment by lytdev** [comment]
当前打开好几个菜单，有功能里面的子菜单，有试验台里面的子菜单，当前激活的是功能的组件首页，再次从标签栏点击试验台首页的时候，左侧的菜单栏的试验台联动激活失效，颜色未变成蓝色

**Comment by Aysnine** [comment]
crud主页也是这样

**Comment by jawnwa22** [comment]
我找到了其中一个原因，是切换侧边栏时，el-menu内部的items对象的键值错误导致的
![image](https://user-images.githubusercontent.com/20170882/78144767-9d20a200-7462-11ea-818a-7ec68748f903.png)

解决方法如下：
手动更改el-menu中的activeIndex为当前的路由即可
![image](https://user-images.githubusercontent.com/20170882/78144899-d0fbc780-7462-11ea-88f1-971f93ad3a9a.png)

**Comment by lytdev** [comment]
![image](https://user-images.githubusercontent.com/13446746/78156053-cea06a00-7470-11ea-9939-356c3551d13b.png)
这在这里文件里嘛？我修改了好像不行呢

**Comment by lytdev** [comment]
> 我找到了其中一个原因，是切换侧边栏时，el-menu内部的items对象的键值错误导致的
> ![image](https://user-images.githubusercontent.com/20170882/78144767-9d20a200-7462-11ea-818a-7ec68748f903.png)
> 
> 解决方法如下：
> 手动更改el-menu中的activeIndex为当前的路由即可
> ![image](https://user-images.githubusercontent.com/20170882/78144899-d0fbc780-7462-11ea-88f1-971f93ad3a9a.png)

按照修改了还是不行，是在哪个文件改的？你的菜单路由是动态的嘛

**Comment by jawnwa22** [comment]
> > 我找到了其中一个原因，是切换侧边栏时，el-menu内部的items对象的键值错误导致的
> > ![image](https://user-images.githubusercontent.com/20170882/78144767-9d20a200-7462-11ea-818a-7ec68748f903.png)
> > 解决方法如下：
> > 手动更改el-menu中的activeIndex为当前的路由即可
> > ![image](https://user-images.githubusercontent.com/20170882/78144899-d0fbc780-7462-11ea-88f1-971f93ad3a9a.png)
> 
> 按照修改了还是不行，是在哪个文件改的？你的菜单路由是动态的嘛

就是在 src/menu-side/index.js 上改的，这个应该和菜单路由是不是动态没有关系的呀

**Comment by jawnwa22** [comment]
我直接在clone的d2-admin项目里加上这段代码也修复了侧边栏无法高亮的问题哦
