### ISSUE TITLE
🤔 提问 | 自定义options 如何获取 vue 中的数据

### ISSUE THREAD

**Issue by zxw7606** [d2-projects/d2-admin#260]
``` js
{
  title: '科目名称',
  key: 'subjectName',
  component: {
    name: 'el-select',
    size: 'mini',
    options: function() {
      console.log(this) // this 为undefined
      var options = []
      for (var sj in subjectList) { // 如何获取 data 下的 subjectList ?
        options.push({
          value: sj.id,
          label: sj.subject_name
        })
      }
      return options
    } ()
  },
  sortable: true
},
```

**Comment by FairyEver** [comment]
``` js
{
  title: '科目名称',
  key: 'subjectName',
  component: {
    name: 'el-select',
    size: 'mini',
    options: () => {
      var options = []
      for (var sj in this.subjectList) {
        options.push({
          value: sj.id,
          label: sj.subject_name
        })
      }
      return options
    } ()
  },
  sortable: true
},
```

使用箭头函数

**Comment by zxw7606** [comment]
`
    computed: {
      columns () {
        return [
          { title: '试卷名称', key: 'paperName', component: { name: 'el-input', size: 'mini' }, sortable: true },
          {
            title: '科目名称', key: 'subjectName', component: {
              name: 'el-select', size: 'mini',
              options: () => {
                let options = []
                for (let sj in this.subjectList) {
                  options.push({
                    value: sj.id,
                    label: sj.subject_name
                  })
                }
                return options
              },
            }, sortable: true
          },
          { title: '题数', key: 'questionNumber', component: { name: 'el-input', size: 'mini' }, sortable: true },
          { title: '分制', key: 'testScore', component: { name: 'el-input', size: 'mini' }, sortable: true },
          { title: '出卷人', key: 'bookMaker', component: { name: 'el-input', size: 'mini' }, sortable: true },
          { title: '创建时间', key: 'createTime', component: { name: 'el-input', size: 'mini' }, sortable: true },
        ]

      }
    },
`

按照你的方法可以了， 但是下拉列表是无数据的，还是不解

**Comment by FairyEver** [comment]
如果你使用的是 d2crud，好像 option 不是这样设置的
参考 https://cdn.d2.pub/d2-admin/preview/index.html#/demo/d2-crud/demo23

**Comment by zxw7606** [comment]
嗯，非常感谢，感觉原因是vue 的computed 一直在循环 导致 数据还没请求到就渲染组件了
