### ISSUE TITLE
关于菜单栏和路由

### ISSUE THREAD

**Issue by cityblack** [d2-projects/d2-admin#261]
用过几个vue的admin框架，大部分的menu和router都是绑定起来。 也就是，直接将menu的配置信息映射到router当中，这样menu和router，只需要维护一个配置便可。 虽然分开来维护可以比较灵活，但是这个基本一致的配置同时维护两份，挺头疼的。感觉这个地方的设计，可以再优化一点。还有关于左边的菜单栏。其实和顶部需要维护的配置也差不多吧，这里只要nemu配置加个字段去标识是否需要在左边栏显示，或则是留一个回调接口，感觉会对二次开发比较友好一点吧

**Comment by FairyEver** [comment]
> 菜单设置的方法 [mutations-headerset](https://www.d2.pub/zh/doc/d2-admin/vuex/menu.html#mutations-headerset) | [mutations-asideset](https://www.d2.pub/zh/doc/d2-admin/vuex/menu.html#mutations-asideset)
> 路由则可以单独设置

作为一个 admin 脚手架项目，如果在项目内就约定 `路由` to `菜单` 的规则，表面看似使用方便，其实这样大大损失了灵活性。在实际的管理后台项目中，往往是在菜单管理中配置菜单，然后前端请求用户菜单后展示菜单数据，同时生成路由。一个 admin 脚手架应该提供细粒度的系统设置 api，开发者可以在一个文件（或者一个函数）内实现**根据实际项目的规则，输入菜单数据，转化为菜单和路由**，然后在每次获得权限菜单时通过这个函数进行一系列的操作。D2Admin 只提供这个方法内需要的和系统互动的接口。

具体实践可以参考：

https://github.com/d2-projects/d2-admin-xiya-go-cms/blob/c9f1515a0bb388ef87f5d5b05637eff9b331325c/src/store/modules/d2admin/modules/permission.js#L146

``` js
async load ({ state, rootState, commit, dispatch }, { focus = false, to = '', data }) {
  // 取消请求 - 没有登录
  if (!data && !rootState.d2admin.user.isLogged) return
  // 取消请求 - 已经加载过动态路由
  if (!focus && state.isLoaded) return
  // 获取接口原始数据
  const source = data || await context.api.MENU_USER()
  // [ 权限 ] 计算权限列表
  state.permissions = getPermissions(source)
  // [ 菜单 ] 计算菜单
  const menus = getMenus(source)
  // [ 菜单 ] 设置顶栏菜单
  commit('d2admin/menu/headerSet', menus, { root: true })
  // [ 菜单 ] 设置侧边栏菜单
  commit('d2admin/menu/asideSet', menus, { root: true })
  // [ 路由 ] 计算路由
  const routes = createRoutesInLayout(getRoutes(source)).concat(routesOutLayout)
  // [ 路由 ] 重新设置路由
  resetRouter(routes)
  // [ 路由 ] 重新设置多标签页池
  commit('d2admin/page/init', routes, { root: true })
  // [ 标签页 ] 重新计算多标签页数据
  dispatch('d2admin/page/openedLoad', { filter: true }, { root: true })
  // [ 搜索 ] 初始化搜索数据
  commit('d2admin/search/init', menus, { root: true })
  // [ 路由 ] 重新访问
  if (to) router.replace(to)
  // 标记已经加载过动态路由
  commit('isLoadedSet', true)
}
```

**Comment by cityblack** [comment]
其实就是加一步映射的问题，实现难度不大，由使用者自己加是可以做到。但是我觉得框架应该便于二次开发。 也就是你在 https://github.com/d2-projects/d2-admin-xiya-go-cms/blob/master/src/store/modules/d2admin/modules/permission.js#L146 中的做法一样，其实多数项目中menu与router绑定映射是约定好的，菜单的可视获取是由后端推送规则，那么可见的列表自然也就是需要加入router当中的。我觉得框架灵活是挺好的，不过有些规则像是成了约定，其实就可以减轻不少工作量。这也就是我提该问题的缘由。个人见解哈哈哈

**Comment by cityblack** [comment]
感谢楼主回答。其实就是加一步映射的问题，实现难度不大，由使用者自己加是可以做到。但是我觉得框架应该便于二次开发。 也就是你在 https://github.com/d2-projects/d2-admin-xiya-go-cms/blob/master/src/store/modules/d2admin/modules/permission.js#L146 中的做法一样，其实多数项目中menu与router绑定映射是约定好的，菜单的可视获取是由后端推送规则，那么可见的列表自然也就是需要加入router当中的。我觉得框架灵活是挺好的，不过有些规则像是成了约定，其实就可以减轻不少工作量。这也就是我提该问题的缘由。个人见解哈哈哈。
