### ISSUE TITLE
🤔 提问 | 数据持久化保存数据错误

### ISSUE THREAD

**Issue by qianyeyixia** [d2-projects/d2-admin#263]
```
🤔 提问 | 数据持久化保存数据错误 Version 1.8
```

 set({ state, dispatch }, data) {
      console.info("data");

      console.info(data);
      return new Promise(async resolve => {
        // store 赋值
        state.info = data;
        // 持久化
        await dispatch(
          "d2admin/db/set",
          {
            dbName: "sys",
            path: "user.info",
            value: data,
            user: true
          },
          { root: true }
        );
        // end
        resolve();
      });
// 保存之后数据异常
{
  "sys": {
    "user": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
        "user": {
          "info": {
            "roleList": [
              {
                "id": -1004,
                "name": "xxxx",
                "remark": "xxxxxx"
              }
            ],
            "roleType": "xxxxxx",
            "userinfo": {
              "roleType": "xxxxx",
              "userId": xxxx,
              "schoolId": xxxx,
              "currentStage": {
                "evaStage": "Result_Open",
                "stage_remark": "xxxxxxxx"
              },
              "currentYearId": 2,
              "hostUrl": "xxxxxxxxxxxxxxxxx",
              "leader": null,
              "school": {
                "id": 123,
                "code": "xxxx",
                "name": "xxxxxxxxx",
                "province": "xxxxxxxxxxx",
                "provinceName": "xxxxxxxx",
                "city": "xxxxxxxxx",
                "cityName": "xxxxxxxxxx市",
                "county": "xxxxxxxxx",
                "countyName": "xxxxxxxxx区",
                "provinceOrg": x,
                "provinceOrgName": "xxxx厅",
                "cityOrg": x,
                "cityOrgName": "x市x",
                "countyOrg": x,
                "countyOrgName": x,
                "areaLevel": "x",
                "type": 2,
                "createTime": "2019-03-04 02:23:17",
                "updateTime": "2020-03-02 02:47:40",
                "tempId": 2,
                "stage": null,
                "groupId": 0,
                "studentCount": xxx
              },
              "teacher": null,
              "parent": null,
              "student": null,
              "adminInfo": null
            }
          }
        },
        "page": {
          "opened": [
            {
              "name": "bench",
              "fullPath": "/bench",
              "meta": {
                "title": "首页",
                "auth": false
              },
              "params": {},
              "query": {}
            }
          ]
        }
      }
    ]
  },
  "database": {}
}

**Comment by qianyeyixia** [comment]
我运行下载好的模板 保存的数据是没问题的

**Comment by FairyEver** [comment]
问题太乱，你的使用方法应该有错误。这部分的文档在 https://www.d2.pub/zh/doc/d2-admin/db/
