### ISSUE TITLE
🤔 提问 | 1.8.0版本,打包文件怎么取消cdn加载

### ISSUE THREAD

**Issue by ChenWeihua123** [d2-projects/d2-admin#266]
我在vue.config.js 里去掉了下面这些代码 ，打包文件运行 报 Vue is not define  求助!! 感谢

`/**
     * 添加 CDN 参数到 htmlWebpackPlugin 配置中
     */
    config.plugin('html').tap(args => {
      if (process.env.NODE_ENV === 'production') {
        // args[0].cdn = cdn
        args[0].cdn = []
      } else {
        args[0].cdn = []
      }
      return args
    })`

**Comment by ChenWeihua123** [comment]
抱歉了 已经看到了配置

**Comment by FairyEver** [comment]
除了在 vue.config.js 修改，还要在 https://github.com/d2-projects/d2-admin/blob/master/public/index.html 去掉 header 里的一些代码

**Comment by ChenWeihua123** [comment]
@FairyEver 谢谢
