### ISSUE TITLE
🤔 提问 | 没有util.ua方法？需要加载什么东西才能用吗？

### ISSUE THREAD

**Issue by 18084** [d2-projects/d2-admin#269]
文档上执行说 util.ua() 就可以了，但是导入的util里面不包含ua方法

**Comment by FairyEver** [comment]
文档上没有更新，最早是有这个方法的，后来去掉了，你可以直接在 https://github.com/d2-projects/d2-admin/blob/master/src/store/modules/d2admin/modules/ua.js 中使用
