### ISSUE TITLE
🤔 提问 | 控制台错误提示

### ISSUE THREAD

**Issue by huangjunjiecn** [d2-projects/d2-admin#270]
git安装简易版本，运行后出现错误提示，求解
如下图：（好像需要翻墙图片才能显示）
<img width="947" alt="error" src="https://user-images.githubusercontent.com/25771244/79249282-9c9af900-7eaf-11ea-9953-fe54dcc50979.PNG">

**Comment by FairyEver** [comment]
试试使用新的这个文件替换一下 https://github.com/d2-projects/d2-admin/blob/master/src/mock/d2-mock/patch/withCredentials.js

**Comment by FairyEver** [comment]
看你的问题报错应该和 #254 是一个问题

**Comment by huangjunjiecn** [comment]
> 试试使用新的这个文件替换一下 https://github.com/d2-projects/d2-admin/blob/master/src/mock/d2-mock/patch/withCredentials.js

嗯，替换之后就没这个错误了。

**Comment by FairyEver** [comment]
防止后续更新丢失这个文件，为后面的人备份此文件内容：

``` js
export default function (Mock) {
  // http://cnine.me/note/FrontEnd/mock-lose-cookies-dbg.html
  Mock.XHR.prototype.__send = Mock.XHR.prototype.send
  Mock.XHR.prototype.send = function () {
    if (this.custom.xhr) {
      this.custom.xhr.withCredentials = this.withCredentials || false
      // https://github.com/d2-projects/d2-admin/issues/254
      if (!this.custom.async) {
        this.custom.xhr.responseType = this.responseType
      }
    }
    this.__send.apply(this, arguments)
  }
}
```

**Comment by huangjunjiecn** [comment]
> 防止后续更新丢失这个文件，为后面的人备份此文件内容：
> 
> ```js
> export default function (Mock) {
>   // http://cnine.me/note/FrontEnd/mock-lose-cookies-dbg.html
>   Mock.XHR.prototype.__send = Mock.XHR.prototype.send
>   Mock.XHR.prototype.send = function () {
>     if (this.custom.xhr) {
>       this.custom.xhr.withCredentials = this.withCredentials || false
>       // https://github.com/d2-projects/d2-admin/issues/254
>       if (!this.custom.async) {
>         this.custom.xhr.responseType = this.responseType
>       }
>     }
>     this.__send.apply(this, arguments)
>   }
> }
> ```

好滴，谢谢。
