### ISSUE TITLE
📔 文档相关 | 可否完善下xlsx导入时，在el-upload中before-upload中返回false后，如何在点击其他的上传按钮触发上传效果？

### ISSUE THREAD

**Issue by jwencode** [d2-projects/d2-admin#271]
再引入了vue-table-import插件后，解析没有问题，但是不知道如何再次点击按钮触发上传效果。

我要实现的功能是，点击上传按钮，解析xlsx文件显示在表格中，点击另一个确定上传按钮正式上传xlsx文件到服务器，请问如何实现。

**Comment by FairyEver** [comment]
before-upload 的回调函数中返回 false 确实可以阻止上传，你可以在这个函数内把收到的 file 参数（也就是选择的文件）存到当前页面实例中的 data 上（比如放在 fileWaitingUpload 字段里），然后在另一个按钮的事件中取得这个数据，再用 axios 或者自己构建一个表单上传。只是把选择的文件暂存在另一个地方，最后上传效果一样。
