### ISSUE TITLE
🤔 提问 | 部署白屏

### ISSUE THREAD

**Issue by 121132839** [d2-projects/d2-admin#278]
我 更改了publicPath:'./' build 之后

部署到NGINX

访问服务器就是白屏！

但是我在本地部署到nginx
用localhost:8080 访问就没有问题
但是用局域网ip:8080访问也是白屏
请问这是什么道理？

**Comment by Aysnine** [comment]
提供下网络请求的截图和 console 日志

**Comment by FairyEver** [comment]
参考 https://cli.vuejs.org/zh/config/#baseurl

**Comment by 121132839** [comment]
哎  原来是路由守卫没写next()  😂

**Comment by Aysnine** [comment]
祝你好运 :)
