### ISSUE TITLE
打包很慢的问题

### ISSUE THREAD

**Issue by cqyzh** [d2-projects/d2-admin#281]
请问有大神遇到过，d2admin打包很慢的问题吗，每次打包都要11多分钟，很抓狂！（我也是才接手前端项目）

**Comment by Aysnine** [comment]
可能是项目太大了，可以做一下打包分析看看什么情况，就是跑 build 的时候传递 --report 参数，在 dist 目录会生成一个 `report.html`，用浏览器打开可以看到。然后针对各个模块做优化，比如合并重复的包、使用 cdn 资源等。

**Comment by wangjue666** [comment]
也有可能是电脑配置偏低
