### ISSUE TITLE
求助 tab页面刷新问题 

### ISSUE THREAD

**Issue by atliwen** [d2-projects/d2-admin#284]
```
 求助 tab页面刷新问题 
```

tab 页面内容不是自己的，而是嵌入的iframe，如何在切换 tab页面 不刷新还保留原先输入的内容

![image](https://user-images.githubusercontent.com/10055836/85272517-d93a3080-b4ae-11ea-9dbc-b57421cb7066.png)

类似 https://segmentfault.com/a/1190000015167850  这个的效果

**Comment by wangjue666** [comment]
已经PR了，可以看看我实现的方式 代码还是很简单的
