### ISSUE TITLE
👾 BUG | 切换路由后，之前打开过的菜单不会自动折叠

### ISSUE THREAD

**Issue by xiebiao360** [d2-projects/d2-admin#285]
动态更改了store里的菜单绑定后，之前打开过的菜单位置，现在处于未折叠的状态

**Comment by DingouerFish** [comment]
也遇到了类似的问题：就算page cache on了，虽然切换回来数据还在，但UI状态（比如滚动条位置）之类的没有重现

**Comment by FairyEver** [comment]
> 也遇到了类似的问题：就算page cache on了，虽然切换回来数据还在，但UI状态（比如滚动条位置）之类的没有重现

滚动条位置不算缓存范围

现在应该没有这个 bug 了，可以在 https://d2.pub/d2-admin/preview/#/demo/playground/store/menu 测试
