### ISSUE TITLE
🤔 提问 | api/index中注入方法的弊端

### ISSUE THREAD

**Issue by Mrlilili** [d2-projects/d2-admin#287]
api入口文件中统一注入各依赖及方法还导致，在api的各modules中无法正确解析到依赖方法，这个有什么好的方案来解决吗？

api/index.js

```js
export default assign({}, ...map(generators, generator => generator({
  service,
  request,
  serviceForMock,
  requestForMock,
  mock,
  faker,
  tools
})))
```

![image](https://user-images.githubusercontent.com/8361655/86216070-0b831680-bbb0-11ea-8325-07c5f7ed847b.png)

**Comment by FairyEver** [comment]
这个应该只是你的 IDE 提示，不影响正常使用

**Comment by CucurbitBaby** [comment]
import { request } from '@/api/service'
