### ISSUE TITLE
主题如何设置默认主题

### ISSUE THREAD

**Issue by YXYCZXY** [d2-projects/d2-admin#288]
如何设置系统登录后 主题为自己设置的默认主题 而不是d2默认主题

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/blob/6a6f920a97c5332b0d74f4ae112ebfed98473f11/src/store/modules/d2admin/modules/theme.js#L10

https://github.com/d2-projects/d2-admin/blob/6a6f920a97c5332b0d74f4ae112ebfed98473f11/src/store/modules/d2admin/modules/theme.js#L47

这些设置更新后 记得清空浏览器的 localstorage，这些默认设置仅仅是在 localstorage 为空的时候生效，生效一次之后，就不会触发这些默认设置了。线上环境可以通过更新版本号来让用户端以前的持久化数据失效。原理见文档 cookie 部分，localstorage 同理 https://d2.pub/zh/doc/d2-admin/util/#util-cookies-set

**Comment by YXYCZXY** [comment]
感谢
