### ISSUE TITLE
🤔 提问 | 简化版如何实现动态路由？

### ISSUE THREAD

**Issue by WangXiuBin123** [d2-projects/d2-admin#293]
目前在简化版的 routes.js 代码中看到的是静态的路由，请问要变成动态路由的话是如何实现呢?

**Comment by wangjue666** [comment]
参考这个 [https://d2.pub/d2-admin/preview/#/demo/playground/add-routes/routes](https://d2.pub/d2-admin/preview/#/demo/playground/add-routes/routes) 以及这个 [https://router.vuejs.org/zh/api/](https://router.vuejs.org/zh/api/)  无非将主动添加路由的逻辑 移动到你需要加载动态路由的时候执行
