### ISSUE TITLE
报错查询不到是什么地方错误

### ISSUE THREAD

**Issue by YXYCZXY** [d2-projects/d2-admin#295]
![image](https://user-images.githubusercontent.com/49504688/88146055-f38e3800-cc2d-11ea-8f26-14c18371bd6b.png)

**Comment by wellenzhong** [comment]
出错提示不是告诉你了吗？
如果没犯错，你这个SipSearch/index.vue里面有一个v-for的遍历，然后指定的key又用了你定义的item,  实在不行你就用index:
`<li v-for="(item,index) in myList" :key="index">{{item.label}}</li>`
