### ISSUE TITLE
🌈 显示优化 | 关于同样的页面，不同的query参数，打开多个tab的问题优化

### ISSUE THREAD

**Issue by ankeji** [d2-projects/d2-admin#297]
在项目终于到同一个路由，但是就query参数的id不同，导致page.js代码判断路由参数的回调失效做进一步优化，

``` javascript
/**
 * @class current
 * @description 打开一个新的页面
 * @param {Object} context
 * @param {Object} payload 从路由钩子的 to 对象上获取 { name, params, query, fullPath, meta } 路由信息
 */
async open ({ state, commit, dispatch }, { name, params, query, fullPath, meta }) {
  // 已经打开的页面
  const opened = state.opened
  // 判断此页面是否已经打开 并且记录位置
  let pageOpendIndex = 0
  const pageOpend = opened.find((page, index) => {
    // ---------- 修改 ----------
    const same = page.fullPath.split('?')[0] === fullPath.split('?')[0]
    // ---------- 历史 ----------
    // const same = page.fullPath === fullPath
    pageOpendIndex = same ? index : pageOpendIndex
    return same
  })
  if (pageOpend) {
    // 页面以前打开过
    await dispatch('openedUpdate', {
      index: pageOpendIndex,
      params,
      query,
      fullPath
    })
  } else {
    // 页面以前没有打开过
    const page = state.pool.find(t => t.name === name)
    // 如果这里没有找到 page 代表这个路由虽然在框架内 但是不参与标签页显示
    if (page) {
      await dispatch('add', {
        tag: Object.assign({}, page),
        params,
        query,
        fullPath
      })
    }
  }
  // 如果这个页面需要缓存 将其添加到缓存设置
  if (isKeepAlive({ meta })) commit('keepAlivePush', name)
  // 设置当前的页面
  commit('currentSet', fullPath)
}
```

**Comment by FairyEver** [comment]
这个地方就是按照不同的 query 打开不同的 tab 的，不过如果有其它人有和你一样的需求（不同 query 打开一个 tab），可以参考你的修改

你的代码里还没涉及到一点是新的路由没有放进 opened 里，以后再点标签的时候 进的还是上次的路由

**Comment by mpandar** [comment]
你好，我遇到了一个类似的问题，当打开多个tab页面 /customer/detail/:id  比如这种，当id不同时会打开不同的tab，但是不同的页面中的数据却是共享的，比如我新打开的一个tab页面，修改了里面的数据，之前打开的tab页面数据也发生了修改，请问这个怎么解决？或者提供下解决思路

**Comment by ankeji** [comment]
你查看一下我提的问题，我好像把代码贴上去了，或者你查看一下D2的代码，特别是跳转路由这一方面

发自我的iPhone

**Comment by mpandar** [comment]
> 你查看一下我提的问题，我好像把代码贴上去了，或者你查看一下D2的代码，特别是跳转路由这一方面 发自我的iPhone
> […](#)
> 在 2020年10月2日，19:54，MaStone ***@***.***> 写道： ﻿ 你好，我遇到了一个类似的问题，当打开多个tab页面 /customer/detail/:id 比如这种，当id不同时会打开不同的tab，但是不同的页面中的数据却是共享的，比如我新打开的一个tab页面，修改了里面的数据，之前打开的tab页面数据也发生了修改，请问这个怎么解决？或者提供下解决思路 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢您的回复，我看了你的代码，您这个问题解决的是，url带有query信息时，不同的query可以跳转到相同的tab，忽略query，我的问题跟你的还不太一样，我是这种带有正则的路由 `/customer/detail/:id` , tab可以打开多个，但是下面的view页面却是一个，所以我不太清楚这是哪里的问题，应该是vue-router的问题，需要查一下，我对vue-router不是太熟悉，所以期望能得到指点

**Comment by ankeji** [comment]
你这个是动态路由，没看错的话你应该是根据不同的id来显示不用的页面，如果是这样的话，那么这个id就是params传的值控制的，这样的话你可以看一下D2的代码，看他封装params跳转路由这一块的代码是怎样实现的，应该可以适当的改一下来解决你的这个问题

发自我的iPhone

**Comment by mpandar** [comment]
> 你这个是动态路由，没看错的话你应该是根据不同的id来显示不用的页面，如果是这样的话，那么这个id就是params传的值控制的，这样的话你可以看一下D2的代码，看他封装params跳转路由这一块的代码是怎样实现的，应该可以适当的改一下来解决你的这个问题 发自我的iPhone
> […](#)
> 在 2020年10月4日，09:25，MaStone ***@***.***> 写道： ﻿ 你查看一下我提的问题，我好像把代码贴上去了，或者你查看一下D2的代码，特别是跳转路由这一方面 发自我的iPhone … 在 2020年10月2日，19:54，MaStone @.***> 写道： ﻿ 你好，我遇到了一个类似的问题，当打开多个tab页面 /customer/detail/:id 比如这种，当id不同时会打开不同的tab，但是不同的页面中的数据却是共享的，比如我新打开的一个tab页面，修改了里面的数据，之前打开的tab页面数据也发生了修改，请问这个怎么解决？或者提供下解决思路 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 感谢您的回复，我看了你的代码，您这个问题解决的是，url带有query信息时，不同的query可以跳转到相同的tab，忽略query，我的问题跟你的还不太一样，我是这种带有正则的路由 /customer/detail/:id , tab可以打开多个，但是下面的view页面却是一个，所以我不太清楚这是哪里的问题，应该是vue-router的问题，需要查一下，我对vue-router不是太熟悉，所以期望能得到指点 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我对vue-router不熟悉，所以就只能一步步一步的查，是动态路由的缓存（keep-alive）问题，现在解决了，我把解决的方案在这里陈诉下，希望对别人有帮助：
keep-alive与vue-router配合的时候，默认是根据vue页面的name进行缓存的，也即只要name一样，那么keep-alive就认为是一样的页面，所以动态路由下`/customer/detail/:id`虽然id不同，但是因为页面的name相同，就导致keep-alive缓存了同样的内容，只需要如下配置下，为router-view配置一个key即可，那么keep-alive会优先使用key来缓存
```
<keep-alive :include="keepAlive">
   <router-view :key="$route.path" />
</keep-alive>
```

**Comment by obrua** [comment]
这个问题我改的是
router.beforeEach里的 
// ---------- 历史 ----------  
// next({ path: to.path, replace: true })  
// ---------- 修改----------  
next({ path: to.fullPath, replace: true })  

我发现page里用的是fullPath，而路由守卫传的时候是用path 丢失了参数~

**Comment by isCopyman** [comment]
> 这个问题我改的是 router.beforeEach里的 // ---------- 历史 ---------- // next({ path: to.path, replace: true }) // ---------- 修改---------- next({ path: to.fullPath, replace: true })
> 
> 我发现page里用的是fullPath，而路由守卫传的时候是用path 丢失了参数~

非常感谢，我发现也是这个原因
