### ISSUE TITLE
🤔 提问 | axios-mock-adapter是不是当前已经过时了

### ISSUE THREAD

**Issue by mmaotai** [d2-projects/d2-admin#299]
想知道当前主流用的mokc工具是什么~

json-server + mockjs?

**Comment by FairyEver** [comment]
请说出你认为 axios-mock-adapter 过时的原因

**Comment by mmaotai** [comment]
axios-mock-adapter  也还好 能模拟数据就好了 只是看到用的人少. 

不发实际的请求  拦截返回数据 得不断console.log 调试起来有点麻烦

webpack-dev-server结合那个axios-mock-adapter可以弄成实际发请求的吗

**Comment by mmaotai** [comment]
> 请说出你认为 axios-mock-adapter 过时的原因
> 
> mock.js 快一年不更新了，而且坑很多
> axios-mock-adapter 一个月内更新的
> 
> 参考对 mockjs 的特殊处理 [090f70e](https://github.com/d2-projects/d2-admin/commit/090f70e5ee1074ad4fa0232212da596818a170fd)


axios-mock-adapter 也还好 能模拟数据就好了 只是看到用的人少.

不发实际的请求 拦截返回数据 得不断console.log 调试起来有点麻烦

webpack-dev-server结合那个axios-mock-adapter可以弄成实际发请求的吗

**Comment by FairyEver** [comment]
> 得不断console.log 调试起来有点麻烦

这个其实你可以用一些全局的设置解决

今年之前我也一直用 mock.js 但是它的全局拦截导致过不少问题，我也收到过很多人遇到的 mockjs 导致的一些资源加载错误。你说的那种方法我没试过，webpack-dev-server 的方法应该也可以，但是就限制住了只在本机开发时可以使用。

**Comment by Aysnine** [comment]
mockjs 已经过时了，类似 in browser 的 mock 可以试试 [miragejs](https://miragejs.com/)，功能强大
