### ISSUE TITLE
强烈建议搞一个精简版出来，必竞90%的用户估计都只是需要一个很简单的后台模版而已。

### ISSUE THREAD

**Issue by arden** [d2-projects/d2-admin#3]
强烈建议搞一个精简版出来，必竞90%的用户估计都只是需要一个很简单的后台模版而已。

**Comment by FairyEver** [comment]
我确实有这个计划，现阶段我先完善一下基础功能，稍后会出一个简化版。
I do have this plan. At this stage, I will improve the basic functions, and later I will make a simplified version.
