### ISSUE TITLE
建议增加路由权限功能

### ISSUE THREAD

**Issue by ChasLui** [d2-projects/d2-admin#30]
建议增加路由权限功能

**Comment by FairyEver** [comment]
我正在思考这个功能应该怎么实现比较好，因为在实际项目中很多情况用户权限是后端配置出来的，不是前端写固定几类权限

**Comment by coldstone** [comment]
@FairyEver 说得太对了，目前很多 admin 框架的权限都是配置在路由文件里的，这个只是前端框架作者一厢情愿的做法，为了实现功能而实现。但实际情况，权限一定是后端配置出来的，可以在页面载入后先通过一个 ajax 请求拿到路由和权限的对应关系，再去渲染菜单和路由。权限无非分为两种：页面级和组件级。

**Comment by FairyEver** [comment]
可以参考此分支实现方式：[https://github.com/d2-projects/d2-admin/tree/dynamic_routes](https://github.com/d2-projects/d2-admin/tree/dynamic_routes)

**Comment by FairyEver** [comment]
2.0 推出时会默认提供一些鉴权方式
