### ISSUE TITLE
请问如何在360兼容模式下实现视图渲染呢

### ISSUE THREAD

**Issue by hqz0129** [d2-projects/d2-admin#304]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 你的标题
```

如果需要，在这里描述具体内容

**Comment by wangjue666** [comment]
专门去搜了下360的兼容模式原理 

> 简单的说360浏览器中包含了两个浏览器
> 一个是IE（Trident内核），即兼容模式，在使用网银时需要切换为兼容模式
> 一个是Chrome（Chrommium内核），即极速模式，普通浏览时使用
>  
>  
> 使用极速模式,就类似与用了360的高速内核,兼容性很好 是谷歌的内核.
>  
> 而使用兼容模式,360的做法是保留了你的电脑里面本身的ie内核,倘若你的电脑浏览器是ie7 ,使用兼容模式,就相当于
> 是使用了ie7,同理,如果你的电脑是ie6,那么兼容就是ie6
>  
> 总结:使用极速浏览器,意味着您正在使用高版本的,使用兼容浏览器,意味着你在使用你电脑里面本身的浏览器.如果你电脑里面的浏览器比较高  那两着  就没有区别了.

所以造成的视图渲染失败原因很大可能是因为IE版本过低 并且vue本身是不支持IE8及以下版本 
如果要兼容IE11 可以参考[这篇文章 ](https://zhuanlan.zhihu.com/p/103907934)折腾折腾
