### ISSUE TITLE
项目会对部分页面进行keepLive，但是我没有在store 找到对应的判断条件

### ISSUE THREAD

**Issue by anthonly** [d2-projects/d2-admin#307]

**Comment by wangjue666** [comment]
你好,是要在 router里面进行配置 , catch参数即为是否要对页面进行keep-alive

```
 children: (pre => [
    {
      path: 'list',
      name: `${pre}list`,
      component: _import('system/user/list'),
      meta: {
        ...meta,
        cache: true,
        title: '用户列表'
      }
    },
  ]
```

**Comment by anthonly** [comment]
![image](https://user-images.githubusercontent.com/45306933/93189104-5c001e00-f774-11ea-85a1-df652276ea99.png)
我项目中是这样使用的但是它没有对页面进行缓存，在store中keepAlive数组中是存在路由name值的，但是页面返回后还是存在刷新的现象

**Comment by wangjue666** [comment]
组件的name 需要跟router定义的name 保存一致 可以去看下示例代码 https://github.com/d2-projects/d2-admin/blob/master/src/views/demo/playground/page-cache/on.vue
