### ISSUE TITLE
建议完善下日志插件

### ISSUE THREAD

**Issue by ChasLui** [d2-projects/d2-admin#31]
实际项目中日志和监控是不可避免的
1. 日志level
2. 错误日志监控上报
3. 统一日志格式 前缀,日期,uuid

**Comment by FairyEver** [comment]
[![](https://api.gh-polls.com/poll/01CHWGFHK63XNPNZFQDBFSYR04/%E6%88%91%E9%9C%80%E8%A6%81%E6%8A%A5%E9%94%99%E6%97%A5%E5%BF%97%E8%AE%B0%E5%BD%95)](https://api.gh-polls.com/poll/01CHWGFHK63XNPNZFQDBFSYR04/%E6%88%91%E9%9C%80%E8%A6%81%E6%8A%A5%E9%94%99%E6%97%A5%E5%BF%97%E8%AE%B0%E5%BD%95/vote)
[![](https://api.gh-polls.com/poll/01CHWGFHK63XNPNZFQDBFSYR04/%E6%88%91%E4%B8%8D%E9%9C%80%E8%A6%81)](https://api.gh-polls.com/poll/01CHWGFHK63XNPNZFQDBFSYR04/%E6%88%91%E4%B8%8D%E9%9C%80%E8%A6%81/vote)

**Comment by FairyEver** [comment]
在 1.1.8 版本已经完成

![](http://fairyever.qiniudn.com/20180807164522.png)

![](http://fairyever.qiniudn.com/20180807164612.png)

![](http://fairyever.qiniudn.com/20180807164653.png)

![](http://fairyever.qiniudn.com/20180807164702.png)
