### ISSUE TITLE
表格中需要渲染表格怎么操作呀

### ISSUE THREAD

**Issue by xujunfeng** [d2-projects/d2-admin#311]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 你的标题
```

如果需要，在这里描述具体内容
表格中需要渲染表格怎么操作呀，在data中加了 component:{'name':'el-avatar'}没有效果

**Comment by wangjue666** [comment]
@xujunfeng  看文档吧 https://d2.pub/zh/doc/d2-crud-v2/columns.html#component-name  可以使用自定义组件包一层
