### ISSUE TITLE
🤔 提问 | 请问如何实现多标签页中标签label的国际化？

### ISSUE THREAD

**Issue by PlasticMemory924** [d2-projects/d2-admin#312]
在使用国际化的过程中，我发现router和i18n在main.js中是同级引用的，所以在router.js中无法使用this.$t，同样在更改标题的钩子函数router.afterEach()中无法使用this.$t，那么如何来实现标签的国际化？

**Comment by FairyEver** [comment]
要在一般的 js 文件中使用 $t 的功能，可以参考 http://kazupon.github.io/vue-i18n/api/#t-key-locale-values

在 VueI18n 实例上可以直接使用相关方法的，项目中 src/i18n.js 直接导出了实例，需要使用的时候导入就可以用

标签国际化我认为有两种方式：如果你的项目是根据后端数据组装动态路由，可以让后端返回数据时进行国际化；第二种方式就是维护 menu 的时候，标签不直接维护汉字，改为维护 i18n 的 path，然后在显示时经过翻译再显示
