### ISSUE TITLE
新建菜单

### ISSUE THREAD

**Issue by ketaoonline** [d2-projects/d2-admin#313]
```
新建菜单
```

kt:
我自己新建了一个菜单，点击的时候左侧没有刷新，用源码里面的就有，是咋回事呢

**Comment by wangjue666** [comment]
![1604045731(1)](https://user-images.githubusercontent.com/24707417/97676282-5f086100-1acb-11eb-89cc-8c0fa9ef2185.jpg)
是指这里吗？  这里配置的是**点击右键弹出的菜单**的数据
