### ISSUE TITLE
🤔 提问 | D2admin框架关于Iframe问题

### ISSUE THREAD

**Issue by wh739789893** [d2-projects/d2-admin#314]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 你的标题
```

在  d2-admin-start-kit/src/layout/header-aside/components/menu-header/index.js  /
 中 this.handleMenuSelect 方法如何拿到   { this.header.map(menu => createMenu.call(this, h, menu)) } menu的值

 <el-menu
            mode="horizontal"
            defaultActive={ this.active }
            onSelect={ this.handleMenuSelect }>
            { this.header.map(menu => createMenu.call(this, h, menu)) }
          </el-menu>

**Comment by wangjue666** [comment]
el-menu 是element组件库提供的, 切换菜单 就会激活onSelect函数回调 更详细的可以看看文档  https://element.eleme.cn/#/zh-CN/component/menu
