### ISSUE TITLE
有一个疑问，就是A列表页进入A编辑页，进入编辑页没有选中菜单

### ISSUE THREAD

**Issue by airzhanglin** [d2-projects/d2-admin#315]
```
🤔 提问 | 有一个疑问，就是A列表页进入A编辑页，进入编辑页没有选中菜单
```

模块A：点击菜单进入A列表页，选中菜单的，这是点击编辑进入A页面的编辑页，这个时候A页面的编辑页跟当前A菜单路由不一样所以没有选中菜单，请问有没有提供方法，来设置选中菜单的

**Comment by wangjue666** [comment]
@airzhanglin  按理来说 **编辑页/详情页** 就不应该充当菜单，非要搞的话，你需要到 `/src/layout/header-aside/components/menu-side/index.js` 下的监听函数中主动做下处理  :smile:
