### ISSUE TITLE
🔩 功能开发 | 是否能接入sentry

### ISSUE THREAD

**Issue by My110202** [d2-projects/d2-admin#321]
现在我的项目中接入了sentry, 但是有些错误不上报,比如打印了一个未定义的变量,都不会发送sentry,同样的配置在其他项目中都是可以用的, 都可以上报的

**Comment by Aysnine** [comment]
先分析下 Vue 的错误捕获，可以发现官方提供了 [`Vue.config.errorHandler`](https://cn.vuejs.org/v2/api/#errorHandler)

D2Admin 也是基于此来捕获错误，并进行手机收集：
https://github.com/d2-projects/d2-admin/blob/e2611b65d53773d048c182fb6806e65a7d805090/src/plugin/error/index.js#L29-L32

Sentry 提供的 Vue 组件捕获，也是基于此：
https://github.com/getsentry/sentry-javascript/blob/a833f0ec0a186f0672a536ea8f7d3b129a71a4fe/packages/vue/src/sdk.ts#L370-L378
