### ISSUE TITLE
🤔 提问 | 如何把vue项目部署到GitHub page上面

### ISSUE THREAD

**Issue by perfectSymphony** [d2-projects/d2-admin#324]
我已经部署到GitHub page上面，但是，遇到一个问题

具体是这样的：
我本地是mock数据调的接口，然后，我部署到GitHub page上面之后，调mock数据的接口或者获取数据报405状态码错误。
请问这个问题怎么解？

**Comment by Aysnine** [comment]
能提供下该 github pages 访问地址吗

**Comment by perfectSymphony** [comment]
https://perfectsymphony.github.io/vue-admin/

**Comment by Aysnine** [comment]
mock 没生效, 如果是生效的 mock，不会有真实的请求发出去，你在代码中注释了

https://github.com/perfectSymphony/vue-admin/blob/29bc860e5417bd49c0ff17296e839afab82d2bd4/src/main.js#L32

**Comment by perfectSymphony** [comment]
非常感谢
