### ISSUE TITLE
求问 其他项目如何引用d2-project呢？ 万分感谢

### ISSUE THREAD

**Issue by fjq8** [d2-projects/d2-admin#325]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 你的标题
```

如果需要，在这里描述具体内容

**Comment by Aysnine** [comment]
能描述下更具体的场景吗

**Comment by fjq8** [comment]
首先感谢回复，就是我现在在做一个项目，用Vue+Element UI写的，但是 我想加入D2-project 中的ueditor功能还有一些其他的D2中的小功能，目前不知道如何加入

**Comment by fjq8** [comment]
**感谢大佬  目前导出文本功能已经引入成功，暂时没有疑惑啦，蟹蟹啦，工作一切顺利**

**Comment by Aysnine** [comment]
你说的应该是你在别的项目中想参考 D2Admin 集成的一些功能，只能具体功能具体分析了
