### ISSUE TITLE
🤔 提问 | 表格组件支持滚动条到底部分页加载吗？

### ISSUE THREAD

**Issue by langhaoabcd** [d2-projects/d2-admin#326]
d2-crud这个组件很好，但是有几个功能好像不支持
1.控制了流体高度，能滚动到底部分页加载吗？
2.筛选某些列的显示和隐藏，列的顺序可以拖拽改变

**Comment by Aysnine** [comment]
1、并不支持滚动分页加载，d2-crud 是基于 el-table 的，el-table 本身就不支持
2、貌似也没提供针对“列的顺序和显示隐藏”的配置面板，可能需要自己实现，可以参考：http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/#/demo/form/toolbar，仓库地址 https://github.com/greper/d2-crud-plus

另外，d2-crud 已经不怎么维护了

**Comment by langhaoabcd** [comment]
谢谢回复，el-table的滚动分页，可以使用自定义指令扩展功能。这有个例子https://blog.csdn.net/baidu_27769027/article/details/101924676




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d2-projects/d2-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 晚上11:27
收件人:&nbsp;"d2-projects/d2-admin"<d2-admin@noreply.github.com&gt;;
抄送:&nbsp;"胡椒粉"<1198754948@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [d2-projects/d2-admin] 🤔 提问 | 表格组件支持滚动条到底部分页加载吗？ (#326)





 
1、并不支持滚动分页加载，d2-crud 是基于 el-table 的，el-table 本身就不支持
 2、貌似也没提供针对“列的顺序和显示隐藏”的配置面板，可能需要自己实现，可以参考：http://preview.d2-crud-plus.docmirror.cn/D2CrudPlusExample/#/demo/form/toolbar，仓库地址 https://github.com/greper/d2-crud-plus
 
另外，d2-crud 已经不怎么维护了

**Comment by Aysnine** [comment]
🉑️👍
