### ISSUE TITLE
🌈 显示优化 | 首页的 tab 页名称好像不能改变，而且编码好像和页面其他文字不一样，导致首页 tab 标签 乱码，其他正常

### ISSUE THREAD

**Issue by jChanJi** [d2-projects/d2-admin#327]

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/blob/98febbfccb113fa89d2660fbb9cd25b6f5854c74/src/setting.js#L22

https://github.com/d2-projects/d2-admin/blob/98febbfccb113fa89d2660fbb9cd25b6f5854c74/src/router/routes.js#L24

"首页"这两个汉字是硬编码，在这两个位置
