### ISSUE TITLE
🤔 提问 | 内嵌网页(iframe)刷新问题

### ISSUE THREAD

**Issue by John-Chan** [d2-projects/d2-admin#333]
比如这个演示页面(https://d2.pub/d2-admin/preview/#/demo/playground/frame/d2-doc) 的效果，切换标签页后，内嵌的网页就会重新加载一次，请问如何才能实现类似keepLive的效果，不让内嵌网页在页面切换时刷新？

我看了文档，没找到相关资料。

**Comment by wangjue666** [comment]
因为iframe是native element, iframe页面中的内容不属于该节点的信息 所以 Keep-alive在这里不起作用.
提供个不重新加载 简单的思路 将iframe 渲染到 <keep-alive>组件外面 监控路由路径 v-show 来控制 iframe的展现
