### ISSUE TITLE
🤔 提问 | chrome断点不能进入到我断点的地方

### ISSUE THREAD

**Issue by WebGuHui** [d2-projects/d2-admin#335]
![image](https://user-images.githubusercontent.com/11729740/116501778-4b0bb380-a8e4-11eb-956f-90700edd4053.png)

我在这里打了一个断点，当触发断点的时候

![image](https://user-images.githubusercontent.com/11729740/116501831-6d9dcc80-a8e4-11eb-9234-cef75b6f5716.png)

会卡在这个地方

**Comment by wangjue666** [comment]
@WebGuHui  vue debugger定位不准确，老问题了，一般的解决方案是在 vue.config.js 加上 
```
configureWebpack: {
  devtool:'souce-map'
}
```
可以试试看, 不行就console大法
