### ISSUE TITLE
在导航栏搜索的时候会报一个错误   v-on handler: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by dongchunfeng** [d2-projects/d2-admin#336]
```
在导航栏搜索的时候会报一个错误   v-on handler: Cannot read property 'value' of undefined
🖐 其它问题 | 你的标题
```
当我搜索菜单时，
![image](https://user-images.githubusercontent.com/37774753/118788142-0f05b600-b8c6-11eb-984f-5ae85d0f8e9d.png)
![image](https://user-images.githubusercontent.com/37774753/118788192-1fb62c00-b8c6-11eb-8525-06da1c0abc8e.png)

这是怎么回事啊  是不是什么冲突了

**Comment by wangjue666** [comment]
@dongchunfeng  可能是你的`menu `中有数据没加标题？ 你可以来定位下`store/search `下的 `pool`数据
