### ISSUE TITLE
🤔 提问 | 作为一个JS刚上手的人，该如何修改它

### ISSUE THREAD

**Issue by GengGode** [d2-projects/d2-admin#337]
作为一个JS刚上手的人，该如何启动运行它
我之前是写C++的，由于某些需求要用网页，刚开始接触Web。
我现在遇到一些问题，我知道clone下来之后运行npm install，但是之后在webStorm里打开public/index.html之后看不到界面的代码，我能够用npm run，在本地打开它，我想了解它的界面以及它的服务端部分在哪，是在一些js文件里面吗？，我如何修改它的登录部分？
作为一个小白，是不是需要先学习一些前提知识才能修改他呢，我现在只会H5和简单的JS。
希望能够得到回复，非常感谢~

As a person who is just getting started with JS, how to start and run it
I wrote C++ before, and I just started to use the Web due to certain needs.
I have some problems now. I know that I run npm install after the clone is down, but after opening public/index.html in webStorm, I can’t see the code of the interface. I can use npm run to open it locally. I want to know about it. Where is the interface and its server part, are they in some js files? , How do I modify its login part?
As a novice, do I need to learn some prerequisite knowledge before modifying him? I only know H5 and simple JS now.
Hope to get a reply, thank you very much~

**Comment by FairyEver** [comment]
> 我知道clone下来之后运行npm install，但是之后在webStorm里打开public/index.html之后看不到界面的代码，我能够用npm run，在本地打开它，我想了解它的界面以及它的服务端部分在哪，是在一些js文件里面吗？，我如何修改它的登录部分？

正确方式应该是 npm i 之后 npm run dev，之后访问 localhost:8080 （如果没有其它服务占用这个端口的话），不应该直接访问 public/index.html

要使用这个模板，前提需要熟悉 vue2.x，vuex 需要了解，网络请求使用的是 axios

一些文档 https://d2.pub/zh/doc/d2-admin/
