### ISSUE TITLE
🖐 其它问题 | 文档里的所有图片都挂了

### ISSUE THREAD

**Issue by MaxChan7** [d2-projects/d2-admin#343]
![](https://tva1.sinaimg.cn/large/008i3skNgy1gsyqt06y63j30hh0bswgc.jpg)

**Comment by Aysnine** [comment]
哪里的文档？[线上](https://d2.pub/zh/doc/d2-admin/learn/start.html#%E6%96%B0%E5%BB%BA%E9%A1%B5%E9%9D%A2)的是好的。

**Comment by MaxChan7** [comment]
> 哪里的文档？[线上](https://d2.pub/zh/doc/d2-admin/learn/start.html#%E6%96%B0%E5%BB%BA%E9%A1%B5%E9%9D%A2)的是好的。

已经恢复了。
