### ISSUE TITLE
页面长度超过一屏，最上面的不能拖拽到最下面

### ISSUE THREAD

**Issue by dolphinfine** [d2-projects/d2-admin#35]
当页面长度很长时，最上面的模块往下拖拽，应该是触发页面滚动条的，然后可以拖拽到最下面。目前只能在可视范围内拖拽。

**Comment by FairyEver** [comment]
哪一个页面？

**Comment by dolphinfine** [comment]
https://fairyever.gitee.io/d2-admin-preview/#/demo/components/layout/grid
先拖拽模块的长度超过页面长度，然后把最上面的模块往下拉，只能拉到可视范围内，超过可视范围的就无法拉到了

**Comment by FairyEver** [comment]
谢谢指出问题，应该是 better-scroll 的滚动机制和 vue-grid-layout 冲突，我想想解决办法

**Comment by FairyEver** [comment]
我修改了这个demo [https://fairyever.gitee.io/d2-admin-preview/#/demo/components/layout/grid](https://fairyever.gitee.io/d2-admin-preview/#/demo/components/layout/grid) 目前所有的 `d2-container` 组件模式中，不开启自定义滚动条的情况只有 `type="full"` `:scroll="false"` 的情况，后续会考虑优化 `d2-container` 组件
