### ISSUE TITLE
建议用flex.css + min-width 做框架的基础布局，不要使用float

### ISSUE THREAD

**Issue by namklaw** [d2-projects/d2-admin#39]
flex.css可以直接写在html里面可以直接控制大致的布局，而min-width可以控制最小宽度不至于错乱。float总有些奇怪的问题…… 比如莫名的间距多了或者少了

**Comment by FairyEver** [comment]
请问具体你发现哪里有问题了，因为布局上只有四个地方用到了float，都是无关紧要的地方

**Comment by namklaw** [comment]
哦～ 那就好，我主要是因为顶栏的菜单的问题，我以为你很多地方用到了，所以才这么说，以后我还是尽量具体问题具体说明～ 顶栏菜单会因为宽度缩小出现错位，所以我改成了flex + 限宽。另外，我比较推荐flex.css 这个通过属性来做布局的插件，可以在html代码层面一目了然地清楚自己的布局。

**Comment by FairyEver** [comment]
顶栏菜单在屏幕过窄的时候换行的问题已经在正在做的下个版本中处理了，方式也是限宽，目前设置了限制1000px最小宽度，等新版本发布的时候上线
