### ISSUE TITLE
建议可以和 ice vue 物料对接起来，用起来更方便，按需组装

### ISSUE THREAD

**Issue by dingyiming** [d2-projects/d2-admin#4]
https://alibaba.github.io/ice/block?type=vue

了解一下 ice vue 物料，可以把模板发布上去，把区块搭建起来，然后我们就很方便的自行组装使用了

**Comment by FairyEver** [comment]
飞冰之前我有过一些了解，幸运的是昨天我已经收到了飞冰开发者的邮件，我们会讨论合作的。如果顺利的话以后大家会在飞冰看到d2admin
I had some understanding of ice. Luckily, I received an email from ice developer yesterday, and we will discuss cooperation. If it goes well, everyone will see d2admin in ice.

**Comment by FairyEver** [comment]
你好啊，我刚发现你就是飞冰的开发者😄

**Comment by FairyEver** [comment]
即将开始
