### ISSUE TITLE
【BUG】Element布局 页面滑动卡顿 && 百万级数据表格是不能滑动吗？

### ISSUE THREAD

**Issue by namklaw** [d2-projects/d2-admin#41]
![image](https://user-images.githubusercontent.com/11420885/42744923-7454e432-8902-11e8-9596-e1f1cf098f8e.png)

环境说明：MAC Chrome
资源地址：
https://fairyever.gitee.io/d2-admin-preview/#/demo/components/bigdata-table
https://fairyever.gitee.io/d2-admin-preview/#/demo/element/basic-layout
详细说明：
1. Element布局页面，滑动中卡顿，卡顿明显；
2. 百万级数据表格无法滑动

**Comment by FairyEver** [comment]
* [basic-layout](https://fairyever.gitee.io/d2-admin-preview/#/demo/element/basic-layout) 这个页面在我电脑上没有卡顿
* 表格那个示例页面的确有 bug 感谢提出，这是没有选择合适的d2-container组件的scroll属性导致的，稍后改正

**Comment by FairyEver** [comment]
数据表格组件下个版本计划去掉，因为组件原作者还没有开发完，如果你有兴趣可以去原项目查看 [https://github.com/lison16/vue-bigdata-table](https://github.com/lison16/vue-bigdata-table)

**Comment by xbc922** [comment]
d2-container组件的scroll属性导致的无法滑动问题如何解决？

**Comment by FairyEver** [comment]
在现在1.1.4版本中，“d2-container组件的scroll属性导致的无法滑动问题” 解决方法是d2-container组件使用“full”模式，1.1.4版本需要这样写：`<d2-container type="full"></d2-container>`，因为card模式和ghost模式都会自动使用优化的滚动条，所以只能使用上述写法。
> 在下个版本中 d2-container 组件的 type 属性默认值更改为 full

**Comment by FairyEver** [comment]
新版本已经发布，d2-container 已经重构
