### ISSUE TITLE
d2-container包含的el-table内容无法选中复制

### ISSUE THREAD

**Issue by xbc922** [d2-projects/d2-admin#43]

**Comment by FairyEver** [comment]
# 在目前的 1.1.4 版本中，这个问题有两个解决办法

## 1 在需要的页面中这样写

> "需要的页面" 可能包含：表单页面，有拖拽操作的页面，需要勾选文字的页面

```
<d2-container type="full">
  内容
</d2-container>
```

不要这样：

```
<d2-container>
  内容
</d2-container>
```

也不要这样：

```
<d2-container type="full" scroll>
  内容
</d2-container>
```

或者这样：

```
<d2-container type="ghost">
  内容
</d2-container>
```

因为只有第一种写法会禁用 better-scroll，你所描述的问题是由于 better-scroll 阻止了事件传递导致的

## 2 修改 [d2-container-full-bs.vue](https://github.com/d2-projects/d2-admin/blob/master/src/components/core/d2-container/components/d2-container-full-bs.vue)：

在下面的位置

https://github.com/d2-projects/d2-admin/blob/070bb9e8a077cb1a8445ea58eaf01f3f92ba1d27/src/components/core/d2-container/components/d2-container-full-bs.vue#L37

之下添加

```
preventDefault: false,
```

添加完成后应该这样：

```
scrollInit () {
  this.BS = new BScroll(this.$refs.wrapper, {
    mouseWheel: true,
    preventDefault: false,
    scrollbar: {
      fade: true,
      interactive: false
    }
  })
}
```

关于为什么加这个参数，见 [https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefault](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefault)

**在下个版本中会对这方面做出优化**

**Comment by FairyEver** [comment]
新版本已经发布，支持自定义 better-scroll 配置项
