### ISSUE TITLE
📔 文档完善 | 增加主题描述和修改主题指导

### ISSUE THREAD

**Issue by FairyEver** [d2-projects/d2-admin#51]

**Comment by wsz7777** [comment]
怎么更换主题

**Comment by FairyEver** [comment]
在这个目录 一个主题一个文件夹 https://github.com/d2-projects/d2-admin/tree/master/src/assets/style/theme

**Comment by wsz7777** [comment]
更换默认的主题，我看到是在body上直接修改class="theme-d2" ==>> class="theme-line"即可。但是没有找到修改他的方法。。。

**Comment by wudicool** [comment]
> 更换默认的主题，我看到是在body上直接修改class="theme-d2" ==>> class="theme-line"即可。但是没有找到修改他的方法。。。
> 
> 就是默认主题怎么换...

现在弄好了吗 我看到修改下配置顺序就行了，或者修改store 里面的返回的下标也行
