### ISSUE TITLE
tab关闭按钮右键点击时报错

### ISSUE THREAD

**Issue by dnyz520** [d2-projects/d2-admin#54]
tab关闭按钮**右键**点击时报错

![tim 20180803221608](https://user-images.githubusercontent.com/29970288/43648100-1040be26-976c-11e8-8c23-c990fb417ce4.png)

**Comment by dnyz520** [comment]
这个已经解决好了.
在/src/layout/header-aside/components/tabs/index.vue行101处增加

`      const attribute = target.getAttribute('aria-controls')

      if (attribute === null) {
        return
      }
`

**Comment by FairyEver** [comment]
已经解决 start-kit 也同步更新
