### ISSUE TITLE
【BUG】baseUrl 设置为根目录 ‘/’ 会报错

### ISSUE THREAD

**Issue by namklaw** [d2-projects/d2-admin#59]
![image](https://user-images.githubusercontent.com/11420885/43703662-106bf908-9990-11e8-8c27-5b5a7e9c6ec1.png)
目录设置成这样

![image](https://user-images.githubusercontent.com/11420885/43703653-078fcc6a-9990-11e8-852a-412372e2b678.png)
目前还在尝试找原因中，确定是因为baseUrl设置导致的这个问题

**Comment by namklaw** [comment]
本地跑会报错，但是放到服务器上就不会报错了……

**Comment by FairyEver** [comment]
重启 dev 服务即可解决
