### ISSUE TITLE
构建完成项目，安装依赖的时候Iceworks占用内存6G多，不知道个别情况还是什么？

### ISSUE THREAD

**Issue by FruitPineapple** [d2-projects/d2-admin#63]
系统win7，选择Vue 模板 D2Admin ICE 构建完成，在安装依赖的时候，内存一下占用高达6G+ 希望有空的时候可以看下

**Comment by FairyEver** [comment]
这个问题你可以向 ice 提一下，我只是做脚手架，ice 的工具问题请向相关人员反映，传送：[https://github.com/alibaba/ice/issues/new](https://github.com/alibaba/ice/issues/new)
