### ISSUE TITLE
登录页内存泄漏和资源浪费

### ISSUE THREAD

**Issue by longxi** [d2-projects/d2-admin#65]
项目登录页使用了 particles.js ，但忘记销毁了，导致登录后依然占用 CPU 资源。
虽然这个登录页基本都会被替换，但前期开发时还是会造成一些浪费，频繁打开登录页的话资源占用更严重。
可以增加钩子
```
beforeDestroy () {
    // 销毁粒子插件实例
    if (pJSDom && pJSDom.length > 0) {
      pJSDom[0].pJS.fn.vendors.destroypJS()
      pJSDom = []
    }
  }
```

refs:
1. [Angular 项目使用 particles.js 增强登录页面](https://czjake.com/blog/article/angular-love-particles)
2. [How to destroy a pJS object](https://github.com/VincentGarreau/particles.js/issues/63)

**Comment by FairyEver** [comment]
感谢你的方案 : ) 代码已经更新

https://github.com/d2-projects/d2-admin/blob/b8e1889bacc80e4838c27db63847b919785dfaa1/src/pages/login/page.vue#L107-L115
