### ISSUE TITLE
双核游览器切换时存在BUG

### ISSUE THREAD

**Issue by dnyz520** [d2-projects/d2-admin#68]
双核或多核游览器进行初次登录,之后进行内核的切换.
那么部分游览器本地数据库数据无法被加载

可能涉及到的数据有标签列表,主题,用户.

![gif](https://user-images.githubusercontent.com/29970288/43874103-73218fc6-9bbc-11e8-8b21-26403c57e5ed.gif)

**Comment by namklaw** [comment]
我看了一下 所谓双核 你可以理解为同时跑两个浏览器，然后地址黏贴复制到另一个浏览器跑…… 所以实际上是有两个存储空间分别存储的。这种情况的解决方案：
考虑到双核不是360独家所有，如果针对每一款双核做对应的sdk，那实在得不偿失。因此，建议这时候最好的方式是把这部分信息存储到服务器，通过与服务器的信息同步，记得切换的时候保存相应状态。【如果非有这方面必要的话】

**Comment by FairyEver** [comment]
这个现象的原因应该是浏览器的不同内核使用的 localstorage 是分开的，所以在一个内核的持久化数据不会在另一个内核中获得
