### ISSUE TITLE
👾 BUG | 在IE或edge下点击收缩按钮报错

### ISSUE THREAD

**Issue by FairyEver** [d2-projects/d2-admin#75]
![](http://fairyever.qiniudn.com/20180809225248.png)

**Comment by dnyz520** [comment]
该问题出现在
src\layout\header-aside\components\menu-side\index.vue
行89中.

当收缩被触发时,将销毁组件,但在销毁的过程中抛出异常,导致下步重新创建组件失败.
所以引起的问题是报错加滚动失效.但奇怪的是Firefox和Chrome内核都正常,唯独Ie异常.所以猜想是better-scroll组件对Ie的支持不够.那么解决方案如下

行89处替换为

        try {
          this.BS.destroy()
        } catch (e) {
          delete this.BS
          this.BS = null
        }

同时受影响的文件还有
src\components\d2-container\components\mixins\bs.js

**Comment by FairyEver** [comment]
谢谢你的建议，代码已经更新 稍后发布 👍
