### ISSUE TITLE
打包部署问题

### ISSUE THREAD

**Issue by CodeDome** [d2-projects/d2-admin#86]
打包完成后在服务器上部署不成功，问题如下：
Failed to load resource: the server responded with a status of 404 (Not Found)
app.e210d0f9.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.a34278a6.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chunk-vendors.ac1865ae.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-007a.26017f54.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-021a.d51a5400.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.e210d0f9.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chunk-vendors.36ccf37e.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.a34278a6.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chunk-vendors.ac1865ae.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-053f.54a22a33.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-072d.e0d647e3.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-074e.689b48e5.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-08d8.c01dc084.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-09fa.4eee6f9d.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-0e82.c37bf9b7.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-0f5f.04d5ba5a.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.a34278a6.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-108e.52e9e9f4.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-10f6.9fc564d3.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-12db.bbfeb3d6.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-1397.418f8b0e.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/d2-admin-preview/css/chunk-163a.1995f30d.css:1 
....

是什么地方没配置对吗

**Comment by FairyEver** [comment]
请检查 `d2-admin/vue.config.js` 中 `baseUrl` 的设置。

`baseUrl` 为项目部署的基础路径，应该以 '/' 开始并且以 '/' 结束

假设你的应用将会部署在域名的根部，比如 https://www.my-app.com/，那么 `baseUrl` 应该值为 '/'

如果你的应用时部署在一个子路径下，那么你需要在这里指定子路径。比如，如果你的应用部署在 https://www.foobar.com/my-app/，那么将这个值改为 `/my-app/`

**Comment by CodeDome** [comment]
好的，谢谢
