### ISSUE TITLE
🤔 提问 | 请问readme里介绍的“支持百万级数据量的表格组件”实际没有吗？没有找到

### ISSUE THREAD

**Issue by lison16** [d2-projects/d2-admin#87]

**Comment by FairyEver** [comment]
那个组件一开始有，后来删掉了，
readme里没有更新，vue-bigdata-table 组件原作者还没有开发完，如果你有兴趣可以去原项目查看 [https://github.com/lison16/vue-bigdata-table](https://github.com/lison16/vue-bigdata-table)
