### ISSUE TITLE
👾 BUG | 卡片布局-滚动优化 footer高度变化后 body-wrapper-inner显示不全

### ISSUE THREAD

**Issue by E00n** [d2-projects/d2-admin#92]

**Comment by FairyEver** [comment]
尝试在 footer 高度变化后手动去触发 d2-container 组件的 `scrollDestroy` 方法，然后再调用 d2-container 组件的`scrollInit` 方法来重新初始化滚动条，或者给 d2-container 组件添加更新 better-scroll 的方法。

**Comment by E00n** [comment]
感谢 问题已解决
在d2-container里添加了updated钩子
updated () {
    this.scrollDestroy()
    this.scrollInit()
  }


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 李杨 <notifications@github.com>
发送时间: Friday, August 31, 2018 4:35:04 PM
收件人: d2-projects/d2-admin
抄送: E00n; Author
主题: Re: [d2-projects/d2-admin] BUG 卡片布局-滚动优化 footer高度变化后 body-wrapper-inner显示不全 (#92)


尝试在 footer 高度变化后手动去触发 d2-container 组件的 scrollDestroy 方法，然后再调用 d2-container 组件的scrollInit 方法来重新初始化滚动条，或者给 d2-container 组件添加更新 better-scroll 的方法。

―

**Comment by E00n** [comment]
感谢 问题已解决 
在d2-container里添加updated
`updated () {
    this.scrollDestroy()
    this.scrollInit()
  }`
