### ISSUE TITLE
🤔 提问 | 请问 同一个路由不同params 如何打开多个tab

### ISSUE THREAD

**Issue by skiphyuk** [d2-projects/d2-admin#96]
如题
比如路由  是edit/1 edit/2 我想动态的在框架内打开两个tab，这种如何处理？
我看现在 tab这里是按照路由的name判断的 ，这样的话相同name就只能打开一个。

**Comment by FairyEver** [comment]
目前的设计的确是根据 name 字段来区分页面的，如果需要满足你的要求，需要从这部分开始改造

https://github.com/d2-projects/d2-admin/blob/c9a454902bfb8d5abc4dad780b34ae38077b70f1/src/store/modules/d2admin/modules/page.js#L37-L66
